### ISSUE TITLE
Hard crash when searching conversations (Expression tree is too large Exception)

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#1796]
Search for "+" or "+*whatever*"
In ConversationListLoader.java 
```JAVA
List<String> numbers = ContactAccessor.getInstance()
          .getNumbersForThreadSearchFilter(filter, context.getContentResolver());
```
returns odd numbers: *EDIT: oops, those are test contact numbers*
![unbenannt](https://cloud.githubusercontent.com/assets/5326916/3822477/78a0645e-1d26-11e4-9ccd-fda31f4a10a7.png)

And then I get 1634 recipient IDs which creates a gigantic SQL statement (see error log).

I was about to propose a change to ThreadDatabase.java
from
```JAVA
    String selection       = RECIPIENT_IDS + " = ?";
    String[] selectionArgs = new String[recipientIds.size()];

    for (int i=0;i<recipientIds.size()-1;i++)
      selection += (" OR " + RECIPIENT_IDS + " = ?");
```
to 
```JAVA
    String selection       = RECIPIENT_IDS + " in (?";
    String[] selectionArgs = new String[recipientIds.size()];

    for (int i=0;i<recipientIds.size()-1;i++)
      selection += (", ?");

    selection += ")";
```
making the statement shorter - but again: to long.
Though this is still too much I believe the statement should be changed like that, for ppl owning a large contact list.

Besides that I guess the getNumbersForThreadSearchFilter in ContactAccessor.java needs to be tweaked to handle the "+" correctly ...

😁 sorry, second last line made me LOL
```
E/SQLiteLog(28749): (1) Expression tree is too large (maximum depth 1000)
W/dalvikvm(28749): threadid=30: thread exiting with uncaught exception (group=0x42d5d140)
E/AndroidRuntime(28749): FATAL EXCEPTION: ModernAsyncTask #5
E/AndroidRuntime(28749): Process: org.thoughtcrime.securesms, PID: 28749
E/AndroidRuntime(28749): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(28749): 	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
E/AndroidRuntime(28749): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(28749): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(28749): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(28749): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(28749): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(28749): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(28749): Caused by: android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000) (code 1): , while compiling: SELECT * FROM thread WHERE recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_ids = ? OR recipient_
D/dalvikvm(28749): GC_FOR_ALLOC freed 1777K, 27% free 15500K/21176K, paused 12ms, total 12ms

```

**Comment by McLoo** [comment]
Can't reproduce this any longer. fine :)
