### ISSUE TITLE
Hard crash while switching preferred network type (NPE)

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#1824]
- had a really bad signal strength
- had a few pending outgoing push messages
- deactivated SMS fallback
- waited a while
- went outside, got a slightly better signal
- switched preferred network type from 3G to 2G 
- bang!

as there where a few more TS crashes(?) and restarts after that I don't have the part 

Some more Exceptions in the complete log: http://hastebin.com/mafapojupo

```
E/AndroidRuntime(22204): FATAL EXCEPTION: SendReceveService-WorkerThread
E/AndroidRuntime(22204): Process: org.thoughtcrime.securesms, PID: 22204
E/AndroidRuntime(22204): java.lang.NullPointerException
E/AndroidRuntime(22204): at org.thoughtcrime.securesms.service.SystemStateListener.isConnected(SystemStateListener.java:53)
E/AndroidRuntime(22204): at org.thoughtcrime.securesms.service.SmsSender.handleSendMessage(SmsSender.java:109)
E/AndroidRuntime(22204): at org.thoughtcrime.securesms.service.SmsSender.process(SmsSender.java:62)
E/AndroidRuntime(22204): at org.thoughtcrime.securesms.service.SendReceiveService$SendReceiveWorkItem.run(SendReceiveService.java:273)
E/AndroidRuntime(22204): at org.thoughtcrime.securesms.util.WorkerThread.run(WorkerThread.java:46)
E/AndroidRuntime( 946): FATAL EXCEPTION: main
E/AndroidRuntime( 946): Process: org.thoughtcrime.securesms, PID: 946
E/AndroidRuntime( 946): java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{41e55e50 V.E..... R......D 0,0-513,243} not attached to window manager
E/AndroidRuntime( 946): at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:370)
E/AndroidRuntime( 946): at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:299)
E/AndroidRuntime( 946): at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
E/AndroidRuntime( 946): at android.app.Dialog.dismissDialog(Dialog.java:329)
E/AndroidRuntime( 946): at android.app.Dialog.dismiss(Dialog.java:312)
E/AndroidRuntime( 946): at org.thoughtcrime.securesms.util.ProgressDialogAsyncTask.onPostExecute(ProgressDialogAsyncTask.java:31)
E/AndroidRuntime( 946): at org.thoughtcrime.securesms.LogSubmitActivity$SubmitToPastebinAsyncTask.onPostExecute(LogSubmitActivity.java:187)
E/AndroidRuntime( 946): at org.thoughtcrime.securesms.LogSubmitActivity$SubmitToPastebinAsyncTask.onPostExecute(LogSubmitActivity.java:144)
E/AndroidRuntime( 946): at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime( 946): at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime( 946): at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime( 946): at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 946): at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 946): at android.app.ActivityThread.main(ActivityThread.java:5139)
E/AndroidRuntime( 946): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 946): at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 946): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
E/AndroidRuntime( 946): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
E/AndroidRuntime( 946): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 946): at dalvik.system.NativeStart.main(Native Method)
--------- beginning of /dev/log/main
```

**Comment by rhodey** [comment]
Was checking in on this and noticed that `SystemStateListener` (source of the NPE) no longer exists on TS master.
