### ISSUE TITLE
NullPointerException in WhisperMessage constructor on 2.3.3 Play Store build

### ISSUE THREAD

**Issue by tavianator** [WhisperSystems/TextSecure#2194]
Every time I enter my password, TextSecure eventually tries to decrypt a particular MMS and then fails with this stack trace:

    java.lang.NullPointerException
           at org.whispersystems.libaxolotl.protocol.WhisperMessage.<init>(WhisperMessage.java:50)
           at org.thoughtcrime.securesms.crypto.MmsCipher.decrypt(MmsCipher.java:64)
           at org.thoughtcrime.securesms.jobs.MmsDownloadJob.storeRetrievedMms(MmsDownloadJob.java:215)
           at org.thoughtcrime.securesms.jobs.MmsDownloadJob.retrieveAndStore(MmsDownloadJob.java:199)
           at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:116)
           at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
           at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
           at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

Ultimately it looks like some invalid Base64 got saved to the DB, which makes [this function](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/util/Base64.java#L1138) return `null` through [this function](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/mms/TextTransport.java#L27) to [here](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/crypto/MmsCipher.java#L60), and then that gets passed to the `WhisperMessage` constructor which NPEs trying to get `serialized.length`.

**Comment by mcginty** [comment]
should be fixed since https://github.com/WhisperSystems/TextSecure/commit/dbd8a4083cc379a00bacfccbc8a3c2dc0ef42d71
