### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2210]
```
E/AndroidRuntime( 6249): FATAL EXCEPTION: main
E/AndroidRuntime( 6249): java.lang.NullPointerException
E/AndroidRuntime( 6249): 	at org.thoughtcrime.securesms.PassphraseChangeActivity.verifyAndSavePassphrases(PassphraseChangeActivity.java:80)
E/AndroidRuntime( 6249): 	at org.thoughtcrime.securesms.PassphraseChangeActivity.access$200(PassphraseChangeActivity.java:40)
E/AndroidRuntime( 6249): 	at org.thoughtcrime.securesms.PassphraseChangeActivity$OkButtonClickListener.onClick(PassphraseChangeActivity.java:124)
E/AndroidRuntime( 6249): 	at android.view.View.performClick(View.java:2485)
E/AndroidRuntime( 6249): 	at android.view.View$PerformClick.run(View.java:9080)
E/AndroidRuntime( 6249): 	at android.os.Handler.handleCallback(Handler.java:587)
E/AndroidRuntime( 6249): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 6249): 	at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 6249): 	at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime( 6249): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6249): 	at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 6249): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime( 6249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 6249): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rhodey** [comment]
seems we have no idea how this happened originally (if we assume src is [this](https://github.com/WhisperSystems/TextSecure/blob/a3f1d9cdfdd32c401bb76a020e3e4e5157212068/src/org/thoughtcrime/securesms/PassphraseChangeActivity.java#L80)) and now this issue has been made really stale by 58664fcddb4933c435d47d1996d80c66224bda4d. I don't feel we benefit from keeping this open any longer.
