### ISSUE TITLE
MediaUtil NPE

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2336]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.net.Uri.getPathSegments()' on a null object reference
at android.content.UriMatcher.match(UriMatcher.java:222)
at org.thoughtcrime.securesms.mms.PartAuthority.getPartStream(PartAuthority.java:40)
at org.thoughtcrime.securesms.util.MediaUtil.getPartData(MediaUtil.java:54)
at org.thoughtcrime.securesms.jobs.SendJob.preparePart(SendJob.java:70)
at org.thoughtcrime.securesms.jobs.SendJob.prepareMessageMedia(SendJob.java:49)
at org.thoughtcrime.securesms.jobs.MmsSendJob.sendMms(MmsSendJob.java:161)
at org.thoughtcrime.securesms.jobs.MmsSendJob.deliver(MmsSendJob.java:120)
at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:69)
at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

**Comment by moxie0** [comment]
@mcginty It also looks like I'm getting null payloads:

```
java.lang.NullPointerException
at javax.crypto.Cipher.doFinal(Cipher.java:1204)
at org.whispersystems.libaxolotl.SessionCipher.getCiphertext(SessionCipher.java:407)
at org.whispersystems.libaxolotl.SessionCipher.encrypt(SessionCipher.java:114)
at org.thoughtcrime.securesms.crypto.MmsCipher.encrypt(MmsCipher.java:100)
at org.thoughtcrime.securesms.jobs.MmsSendJob.getEncryptedMessage(MmsSendJob.java:186)
at org.thoughtcrime.securesms.jobs.MmsSendJob.sendMms(MmsSendJob.java:153)
at org.thoughtcrime.securesms.jobs.MmsSendJob.deliver(MmsSendJob.java:120)
at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:69)
at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```
