### ISSUE TITLE
Sending pics (push) almost always fails (with log)

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2351]
I wanted to send 6 photos to a friend of mine and it took forever. Sending photos over push fails WAY, WAY too often. It's a constand failure. Plus, when I "resend" the messages they are sent as MMS even if I have it *disabled* in the settings.
Don't know what's wrong with textsecure but here is the log: https://gist.github.com/anonymous/ec2cd468fe60e523c448
Thank you

**Comment by manhole11** [comment]
This is a self perpetuating problem... messages don't get delivered, so I have to take screenshots of what I wrote (to avoid resending each message again, one at a time). But the screenshots don't get through either, because they keep failing and they make the app crash etc... so basically, it's impossible to communicate.
Here is a screenshot of yet another problem -- I try to send a photo via push but it's not even displayed. It won't even let me post logs any more, it says it was impossible to grab it from my device.
It will be hard to convince all my friends to switch to yet another app. Whispersystems has been a great disappointment. Very sorry to admit it.
![media-20150118](https://cloud.githubusercontent.com/assets/6691301/5792056/5220d290-9f04-11e4-8aec-9bef0f506886.png)

**Comment by peterpanondrugs** [comment]
same here: 
its fails kinda each time! that's for each version:
Device : samsung SHV-E250K (t0ltektt)
Android: JZO54K.E250KKKVMK2
OS Host: SEP-84
App : TextSecure 2.4.2 

https://gist.github.com/b8b62aa1fe44b7a5f630

**Comment by wewondr** [comment]
same here²:
sending pictures often fails, resend sends the message through mms even if I have it disabled in the settings.

Device : Sony D5503 (D5503)
Android: 14.4.A.0.108
OS Host: BuildHost
App : TextSecure 2.5.3 
https://gist.github.com/anonymous/fe02fb873cf67519b912

Device : HTC HTC Desire 310 (htc_europe)
Android: 1.00.401.14
OS Host: vBuild1LX83
App : TextSecure 2.5.3 
https://gist.github.com/anonymous/deda8c7a7ce77903bbd9

**Comment by mcginty** [comment]
```
W/PushMediaSendJob(27501): javax.net.ssl.SSLException: Write error: ssl=0x608fb268: I/O error during system call, Broken pipe
W/PushMediaSendJob(27501): 	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_write(Native Method)
W/PushMediaSendJob(27501): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:693)
W/PushMediaSendJob(27501): 	at java.io.OutputStream.write(OutputStream.java:82)
W/PushMediaSendJob(27501): 	at libcore.net.http.HttpEngine.writeRequestHeaders(HttpEngine.java:646)
W/PushMediaSendJob(27501): 	at libcore.net.http.HttpEngine.initRequestBodyOut(HttpEngine.java:346)
W/PushMediaSendJob(27501): 	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:301)
W/PushMediaSendJob(27501): 	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
W/PushMediaSendJob(27501): 	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
W/PushMediaSendJob(27501): 	at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
W/PushMediaSendJob(27501): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:390)
W/PushMediaSendJob(27501): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:303)
W/PushMediaSendJob(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:217)
W/PushMediaSendJob(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:201)
W/PushMediaSendJob(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:104)
W/PushMediaSendJob(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:83)
W/PushMediaSendJob(27501): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:120)
W/PushMediaSendJob(27501): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:69)
W/PushMediaSendJob(27501): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
W/PushMediaSendJob(27501): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushMediaSendJob(27501): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/PushMediaSendJob(27501): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/JobConsumer(27501): org.thoughtcrime.securesms.transport.RetryLaterException: javax.net.ssl.SSLException: Write error: ssl=0x608fb268: I/O error during system call, Broken pipe
W/JobConsumer(27501): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:129)
W/JobConsumer(27501): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:69)
W/JobConsumer(27501): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
W/JobConsumer(27501): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/JobConsumer(27501): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/JobConsumer(27501): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/JobConsumer(27501): Caused by: javax.net.ssl.SSLException: Write error: ssl=0x608fb268: I/O error during system call, Broken pipe
W/JobConsumer(27501): 	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_write(Native Method)
W/JobConsumer(27501): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:693)
W/JobConsumer(27501): 	at java.io.OutputStream.write(OutputStream.java:82)
W/JobConsumer(27501): 	at libcore.net.http.HttpEngine.writeRequestHeaders(HttpEngine.java:646)
W/JobConsumer(27501): 	at libcore.net.http.HttpEngine.initRequestBodyOut(HttpEngine.java:346)
W/JobConsumer(27501): 	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:301)
W/JobConsumer(27501): 	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
W/JobConsumer(27501): 	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
W/JobConsumer(27501): 	at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
W/JobConsumer(27501): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:390)
W/JobConsumer(27501): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:303)
W/JobConsumer(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:217)
W/JobConsumer(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:201)
W/JobConsumer(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:104)
W/JobConsumer(27501): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:83)
W/JobConsumer(27501): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:120)
W/JobConsumer(27501): 	... 5 more
```

applicable: there's apparently an Android bug that returns back closed connections sometimes that may cause the issue. https://code.google.com/p/android/issues/detail?id=65463

**Comment by mcginty** [comment]
Closing and making a libtextsecure bug instead

**Comment by mcginty** [comment]
for linkability https://github.com/WhisperSystems/libtextsecure-java/issues/1
