### ISSUE TITLE
share / add attachment: picture == > crash

### ISSUE THREAD

**Issue by peterpanondrugs** [WhisperSystems/TextSecure#2372]
same problem still existing! .... was closed on thread #2248 
(i didnt know if should open a new one again or post in closed. couldnt find in guidelines)
what happened there on the closed thread? i dont see the progress.
cheers 

Device : Samsung GT-I9305 (m3xx)
Android: omni_i9305-userdebug 4.4.4 KTU84P 440 test-keys
App : TextSecure 2.4.2

 when i send a picture from gallery / or as attachment out of TS or from my camera. it crashes. can someone confirm this? 
log: https://gist.github.com/d0195640abc36b4f8cf5

**Comment by mcginty** [comment]
You did fine opening a new issue :). Sorry you're still hitting this. Pasting the related part (OOM):

```
D/dalvikvm( 4164): GC_BEFORE_OOM freed 79K, 49% free 17815K/34420K, paused 46ms, total 46ms
E/dalvikvm-heap( 4164): Out of memory on a 31961104-byte allocation.
I/dalvikvm( 4164): "JobConsumer-1" prio=5 tid=13 RUNNABLE
I/dalvikvm( 4164):   | group="main" sCount=0 dsCount=0 obj=0x423bb318 self=0x5cd0ba30
I/dalvikvm( 4164):   | sysTid=4203 nice=0 sched=0/0 cgrp=apps handle=1557184136
I/dalvikvm( 4164):   | state=R schedstat=( 6746567746 16561401629 3732 ) utm=631 stm=43 core=3
I/dalvikvm( 4164):   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
I/dalvikvm( 4164):   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
I/dalvikvm( 4164):   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:620)
I/dalvikvm( 4164):   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:138)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:102)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:93)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(BitmapUtil.java:83)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBytes(BitmapUtil.java:41)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.mms.MediaConstraints.getResizedMedia(MediaConstraints.java:63)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.jobs.SendJob.resizePart(SendJob.java:85)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.jobs.SendJob.preparePart(SendJob.java:66)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.jobs.SendJob.prepareMessageMedia(SendJob.java:49)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:113)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:69)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
I/dalvikvm( 4164):   at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
I/dalvikvm( 4164):   at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
I/dalvikvm( 4164):   at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

We might have bitmap leak or some kind of memory leak if we have OOMs on a newer devices like the S3.

**Comment by savewolfs** [comment]
My nexus 5 I'd doing the same it didn't crash but when I try to send a picture I get a red triangle and error saying message failed to send but not why been like this for about a month I have uninstalled and reinstall ed it stl dissent work help please

**Comment by mcginty** [comment]
@savewolfs that sounds like a separate issue, please post it in its own issue and include a debug log

**Comment by d8ag8r** [comment]
@mcginty  I'm having the same issue as @savewolfs . I've opened issue #2451 and attached the log.

**Comment by mcginty** [comment]
Thanks!
