### ISSUE TITLE
Downloading encrypted MMS fails

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#2419]
I've just noticed that I cannot download encrypted MMS anymore. I'd I attempt to, the message "connecting to the server" stays forever and nothing more happens. Additionally, if I send an MMS to myself the conversation list preview tells me there is a faulty encrypted message. This might be unrelated.
Log: https://gist.github.com/53596a5b7455de8e99d8
I read related issues and didn't find an exact match to this problem. If I missed one, I I'm sorry for the duplication.

**Comment by merkste** [comment]
A colleague of mine has sent me another MMS for testing purposes, which got downloaded immediately. Therefore I suspect the problem could be caused either by
* an older TS version sending the MMS
* the occurrence of an error on the first download attempt that is never recovered.

However, I am just speculating.

**Comment by agrajaghh** [comment]
relevant part:
```
W/PduParser( 5660): Parsing parts...
W/MmsCipher( 5660): Attempting truncated decrypt...
W/MmsDownloadJob( 5660): org.whispersystems.libaxolotl.InvalidMessageException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either than the input has been truncated or that an embedded message misreported its own length.
W/MmsDownloadJob( 5660): at org.whispersystems.libaxolotl.protocol.WhisperMessage.<init>(WhisperMessage.java:79)
W/MmsDownloadJob( 5660): at org.thoughtcrime.securesms.crypto.MmsCipher.decrypt(MmsCipher.java:74)
W/MmsDownloadJob( 5660): at org.thoughtcrime.securesms.jobs.MmsDownloadJob.storeRetrievedMms(MmsDownloadJob.java:215)
W/MmsDownloadJob( 5660): at org.thoughtcrime.securesms.jobs.MmsDownloadJob.retrieveAndStore(MmsDownloadJob.java:199)
W/MmsDownloadJob( 5660): at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:116)
W/MmsDownloadJob( 5660): at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/MmsDownloadJob( 5660): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/MmsDownloadJob( 5660): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/MmsDownloadJob( 5660): Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either than the input has been truncated or that an embedded message misreported its own length.
W/MmsDownloadJob( 5660): at com.google.protobuf.CodedInputStream.readRawBytes(CodedInputStream.java:789)
W/MmsDownloadJob( 5660): at com.google.protobuf.CodedInputStream.readBytes(CodedInputStream.java:329)
W/MmsDownloadJob( 5660): at org.whispersystems.libaxolotl.protocol.WhisperProtos$WhisperMessage.<init>(WhisperProtos.java:122)
W/MmsDownloadJob( 5660): at org.whispersystems.libaxolotl.protocol.WhisperProtos$WhisperMessage.<init>(WhisperProtos.java:57)
W/MmsDownloadJob( 5660): at org.whispersystems.libaxolotl.protocol.WhisperProtos$WhisperMessage$1.parsePartialFrom(WhisperProtos.java:155)
W/MmsDownloadJob( 5660): at org.whispersystems.libaxolotl.protocol.WhisperProtos$WhisperMessage$1.parsePartialFrom(WhisperProtos.java:150)
W/MmsDownloadJob( 5660): at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:141)
W/MmsDownloadJob( 5660): at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:176)
W/MmsDownloadJob( 5660): at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:188)
W/MmsDownloadJob( 5660): at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:193)
W/MmsDownloadJob( 5660): at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
W/MmsDownloadJob( 5660): at org.whispersystems.libaxolotl.protocol.WhisperProtos$WhisperMessage.parseFrom(WhisperProtos.java:309)
W/MmsDownloadJob( 5660): at org.whispersystems.libaxolotl.protocol.WhisperMessage.<init>(WhisperMessage.java:63)
W/MmsDownloadJob( 5660): ... 7 more 
```

**Comment by merkste** [comment]
It could perfectly be the case that the log is non-representative for the error since it only logs the self-send which might fail due to different reasons. Unfortunately I do not have a log of the download attempts happening if others send me a message.

**Comment by merkste** [comment]
Tests with a feature phone:
* umts:
works
fine
* umts, vpn Opera Max:

* wlan:

download button, attempt  to connect, button reappears, download successful after switching to umts
https://gist.github.com/557aa76cfe2b89004646

**Comment by merkste** [comment]
https://gist.github.com/80c60bdce5e450f0517a

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has since been removed, if this problem still occurs with plaintext MMS or media messages sent over the push channel (colored blue) please let us know and this issue will be reopened.
