### ISSUE TITLE
Material Crashes?

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2424]
Could be related to reviews like this one?
https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&reviewId=Z3A6QU9xcFRPRzNQamRUVHhkY1psVV9zVXRPMU9hSHRfLThjZ3JUcFNibzlCaWs1YlZuM1M4azh0Sjl3cVdWRDk4TkpJbm9qV3ZDc2x2RW8yXzZnWDRMQlE

`````
java.lang.NullPointerException
at com.android.internal.policy.impl.PhoneWindow.onKeyUpPanel(PhoneWindow.java:987)
at com.android.internal.policy.impl.PhoneWindow.onKeyUp(PhoneWindow.java:1686)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2097)
at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3618)
at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3588)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2834)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4849)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method)
`````

Also:

`````
java.lang.NullPointerException
at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:440)
at com.android.internal.policy.impl.PhoneWindow.onKeyDownPanel(PhoneWindow.java:772)
at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1437)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1831)
at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3577)
at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3547)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2797)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4774)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
at dalvik.system.NativeStart.main(Native Method)
`````

**Comment by mcginty** [comment]
Yeah, it looks related to https://code.google.com/p/android/issues/detail?id=78154. I think we have to re-add that LG workaround weirdness. Is it possible to see which phone models are related to the crashes?

**Comment by moxie0** [comment]
Didn't this happen last time?

Looking at the crashes, it's some LG but also other weird devices.

**Comment by mcginty** [comment]
Yeah, the workaround requires overriding `onKeyDown` and `onKeyUp` on all activities, and the decision was to ignore it since it was too much of a hack and had some potential performance implications from doing more work with every keypress.

**Comment by moxie0** [comment]
My recollection is that the decision was to roll back the change.  We
can't release software that just crashes.

On 02/07/2015 11:15 PM, Jake McGinty wrote:
> Yeah, the workaround requires overriding |onKeyDown| and |onKeyUp| on
> all activities, and the decision was to ignore it since it was too much
> of a hack and had some potential performance implications from doing
> more work with every keypress.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/2424#issuecomment-73400042>.
> 

-- 
http://www.thoughtcrime.org

**Comment by mcginty** [comment]
Yes, I was remembering the discussion to not keep it just in case after we reverted to v20. My mistake.
