### ISSUE TITLE
Not receiving any messages while connected to mobile web 

### ISSUE THREAD

**Issue by Attaqua** [WhisperSystems/TextSecure#2469]
While connected to mobile web sending messages seems to be possible, but I don't see any answers.
Please see the following bug report:
https://gist.github.com/dfe0e0db9f0c3c7dac76

**Comment by agrajaghh** [comment]
looks like problems with gcm. Are you using a custom rom?

**Comment by Attaqua** [comment]
Nope

**Comment by mcginty** [comment]
```
W/GcmRefreshJob( 6667): GCM registrationId expired, reregistering...
W/JobConsumer( 6667): java.io.IOException: SERVICE_NOT_AVAILABLE
W/JobConsumer( 6667): at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
W/JobConsumer( 6667): at org.thoughtcrime.securesms.jobs.GcmRefreshJob.onRun(GcmRefreshJob.java:66)
W/JobConsumer( 6667): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/JobConsumer( 6667): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/GcmRefreshJob( 6667): GCM reregistration failed after retry attempt exhaustion! 
```
