### ISSUE TITLE
Crash Browser -- APN Exception

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2506]
`````
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:200)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)
Caused by: android.database.sqlite.SQLiteException: attempt to write a readonly database
at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
at android.database.sqlite.SQLiteDatabase.<init>(SQLiteDatabase.java:1858)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:829)
at org.thoughtcrime.securesms.database.ApnDatabase.<init>(ApnDatabase.java:92)
at org.thoughtcrime.securesms.database.ApnDatabase.getInstance(ApnDatabase.java:76)
at org.thoughtcrime.securesms.mms.MmsConnection.getLocalApn(MmsConnection.java:61)
at org.thoughtcrime.securesms.mms.MmsConnection.getApn(MmsConnection.java:77)
at org.thoughtcrime.securesms.mms.OutgoingMmsConnection.isConnectionPossible(OutgoingMmsConnection.java:108)
at org.thoughtcrime.securesms.ConversationActivity$8.doInBackground(ConversationActivity.java:716)
at org.thoughtcrime.securesms.ConversationActivity$8.doInBackground(ConversationActivity.java:713)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
... 4 more
`````

**Comment by moxie0** [comment]
Confirmed this is still happening in 2.6.4

**Comment by mcginty** [comment]
Can you check the CrashBrowser and see if there's a correlation to a specific manufacturer or device?

**Comment by mcginty** [comment]
Right now there's not enough info to act on, removing the milestone.

**Comment by moxie0** [comment]
This is a partial list of devices:

ME632
Galaxy Proclaim (SCH-S720C)
N860 (arthur)
Galaxy Q (SGH-T589W)
Galaxy S (GT-I9000)
Wildfire S (marvel)
ZTE V791 (P175A40)

I think a full stack trace is at minimum enough info to stop the app from crashing on people.

**Comment by moxie0** [comment]
Still happening with 2.9.3
