### ISSUE TITLE
Crash Browser -- MMS Send Exception

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2509]
`````
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:864)
Caused by: java.lang.NullPointerException
at ws.com.google.android.mms.pdu.PduHeaders.setEncodedStringValues(PduHeaders.java:634)
at ws.com.google.android.mms.pdu.SendReq.setTo(SendReq.java:298)
at org.thoughtcrime.securesms.database.MmsDatabase.insertMessageOutbox(MmsDatabase.java:685)
at org.thoughtcrime.securesms.sms.MessageSender.send(MessageSender.java:103)
at org.thoughtcrime.securesms.ConversationActivity$14.doInBackground(ConversationActivity.java:1088)
at org.thoughtcrime.securesms.ConversationActivity$14.doInBackground(ConversationActivity.java:1085)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
`````

**Comment by moxie0** [comment]
Looks like this was fixed with #2521
