### ISSUE TITLE
CrashBrowser: Character Calculation NPE

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2608]
`````
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5146)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.thoughtcrime.securesms.ConversationActivity.calculateCharactersRemaining(ConversationActivity.java:960)
at org.thoughtcrime.securesms.ConversationActivity.access$1500(ConversationActivity.java:122)
at org.thoughtcrime.securesms.ConversationActivity$ComposeKeyPressedListener.afterTextChanged(ConversationActivity.java:1216)
at android.widget.TextView.sendAfterTextChanged(TextView.java:7424)
at android.widget.TextView.setText(TextView.java:3822)
at android.widget.TextView.setText(TextView.java:3671)
at android.widget.EditText.setText(EditText.java:80)
at android.widget.TextView.setText(TextView.java:3646)
at org.thoughtcrime.securesms.ConversationActivity.initializeDraft(ConversationActivity.java:628)
at org.thoughtcrime.securesms.ConversationActivity.onCreate(ConversationActivity.java:179)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
... 12 more
`````

**Comment by moxie0** [comment]
da75268545c164fb19f36f445020028d005b3830
