### ISSUE TITLE
can't send/receive encypted push even after re-register

### ISSUE THREAD

**Issue by clsec** [WhisperSystems/TextSecure#2688]
I am having the same problem again as #2609 which was closed.

TS looks to be sending encrypted push but the recipient isn't receiving and I get no check box. I also can not receive encrypted push. This is happening both before and after re-registering with the server.

Note II, stock ROM, Android 4.4.2, TS 2.6.4

log: https://gist.github.com/834122f2fa3d2e54ad9f

**Comment by agrajaghh** [comment]
looks like some connectivity issues:

```` 
W/MessageRetrievalService(21240): java.util.concurrent.TimeoutException: Timeout exceeded
W/MessageRetrievalService(21240): 	at org.whispersystems.textsecure.internal.websocket.WebSocketConnection.readRequest(WebSocketConnection.java:77)
W/MessageRetrievalService(21240): 	at org.whispersystems.textsecure.api.TextSecureMessagePipe.read(TextSecureMessagePipe.java:72)
W/MessageRetrievalService(21240): 	at org.thoughtcrime.securesms.service.MessageRetrievalService.run(MessageRetrievalService.java:79)
W/MessageRetrievalService(21240): 	at java.lang.Thread.run(Thread.java:841)
W/MessageRetrievalService(21240): Network requirement: true, active activities: 1, push pending: true
W/MessageRetrievalService(21240): Reading message...
```

**Comment by clsec** [comment]
Yeah, it seems a reboot was in order. My bad.
