### ISSUE TITLE
CrashBrowser: ContactsDatabase NPE

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2722]
I have a feeling this is people fucking with their phones:

`````
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
at org.thoughtcrime.securesms.contacts.ContactsDatabase$TypedCursorWrapper.<init>(ContactsDatabase.java:237)
at org.thoughtcrime.securesms.contacts.ContactsDatabase.queryAndroidDb(ContactsDatabase.java:144)
at org.thoughtcrime.securesms.contacts.ContactsDatabase.query(ContactsDatabase.java:110)
at org.thoughtcrime.securesms.contacts.ContactsCursorLoader.loadInBackground(ContactsCursorLoader.java:46)
at org.thoughtcrime.securesms.contacts.ContactsCursorLoader.loadInBackground(ContactsCursorLoader.java:28)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
`````

**Comment by mcginty** [comment]
I have that feeling, too. The standard Android query for a contacts list is returning null. I guess either way we shouldn't crash.
