### ISSUE TITLE
Crash on verify contact

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#2853]
This dialog is currently broken:
![screenshot_2015-04-01-23-25-44](https://cloud.githubusercontent.com/assets/5296073/6953194/04773b30-d8c8-11e4-9b38-92444a107f88.png)

I have a fix for the design issue (#2821) but I couldn't figure out why its crashing when you click on verify. I guess this happend after the routing logic commit 0ff99258acd8e125ae902ff749f93e05c6f8ecb0 

````
    27147-27147/org.thoughtcrime.securesms E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms, PID: 27147
    java.lang.RuntimeException: Unable to resume activity {org.thoughtcrime.securesms/org.thoughtcrime.securesms.VerifyIdentityActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.Locale.equals(java.lang.Object)' on a null object reference
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2951)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.Locale.equals(java.lang.Object)' on a null object reference
            at org.thoughtcrime.securesms.util.DynamicLanguage.onResume(DynamicLanguage.java:24)
            at org.thoughtcrime.securesms.KeyScanningActivity.onResume(KeyScanningActivity.java:56)
            at org.thoughtcrime.securesms.VerifyIdentityActivity.onResume(VerifyIdentityActivity.java:73)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
            at android.app.Activity.performResume(Activity.java:6019)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
````

**Comment by 2-4601** [comment]
Sorry, if reporting on this issue is no appropriate but the registration problems dialog is similarly broken (except there are no crashes, just a broken design):
![screenshot_2015-04-03-06-12-14](https://cloud.githubusercontent.com/assets/174176/6988271/5e96270c-da58-11e4-9b4f-504df8c236d2.png)

Unfortunately I do not have an English screenshot at the moment. I run into this yesterday while setting up another device for testing purposes.
The greyed text 'Mahdollisia ongelmia' is the string 'Possible problems' at Transifex (RegistrationProblemsActivity_possible_problems).

Android 4.0.4, TS 2.9.3

**Comment by agrajaghh** [comment]
@2-4601 I guess it's best to open a new issue for that
