### ISSUE TITLE
file not found exception when sharing images sometimes

### ISSUE THREAD

**Issue by oholika** [WhisperSystems/TextSecure#2901]
This is one is tough to reproduce but annoying me on a regular basis: make a picture with the LRX22C default camere app and share with a TS 2.9.3 user or group. sometimes the picture has not been added to the conversation; nevertheless if I close the conversation it has been saved as draft including the picture.

https://gist.github.com/4c60101d574e51657f1f

**Comment by WhiteHatTux** [comment]
I had a similar problem just now. As far as i saw the picture was not added as draft. 
I took a picture from another app, shared it into Textsecure (which i hadn't opened in a day and had to enter the password) and once i got past the password screen i was just taken to the conversation screen. The shared picture got lost. Sadly i was not able to reproduce it and don't have a logcat. :-(

**Comment by mcginty** [comment]
relevant log section:

```
E/BitmapFactory(21512): Unable to decode stream: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
W/BitmapDrawable(21512): BitmapDrawable cannot decode 
W/ImageSlide(21512): Got soft reference: null
W/ImageSlide(21512): getThumbnail() resolving thumbnail, as it wasn't cached
W/MediaUtil(21512): generating thumbnail for new part
W/BitmapUtil(21512): rough scale 3264x2448 => 816x612
W/BitmapUtil(21512): fine scale 816x612 => 460x345
I/CameraExif(21512): Orientation not found
W/MediaUtil(21512): generated thumbnail for part, 460x345 (1,333:1) in 236ms
W/ImageSlide(21512): thumbnail decode/generate time: 252ms
```

**Comment by rhodey** [comment]
@oholika & @WhiteHatTux do you remember if the image you were trying to share was synced with Google Drive or any other cloud sync type thing? I've run into a similar issue when trying to send google drive images from TextSecure-- maybe related.

**Comment by oholika** [comment]
No, I don't sync my pictures with cloud services. But I can confirm it's more likely to happen if I share e.g. Pictures from a website.

**Comment by WhiteHatTux** [comment]
Sorry, I don't recall the exact situation. It might have been shared from owncloud, but am not sure about that.

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by 2-4601** [comment]
Sharing a photo from the stock gallery app on Moto G (2nd gen) running Lollipop sometimes fails. Let's say 1-10 % of the time. This is my contact's device so I can't reproduce or debug and I'll just leave this here.

https://gist.github.com/anonymous/191d87ebdf55a121e1cacb069117ebca
```
W DecryptableStreamLocalUriFetcher: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_captures/1468912320871.blob: open failed: ENOENT (No such file or directory)
W DecryptableStreamLocalUriFetcher: 	at libcore.io.IoBridge.open(IoBridge.java:452)
W DecryptableStreamLocalUriFetcher: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.crypto.DecryptingPartInputStream.<init>(DecryptingPartInputStream.java:62)
W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.providers.PersistentBlobProvider.getStream(PersistentBlobProvider.java:128)
W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:54)
W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:32)
W DecryptableStreamLocalUriFetcher: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:16)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W DecryptableStreamLocalUriFetcher: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W DecryptableStreamLocalUriFetcher: 	at java.lang.Thread.run(Thread.java:818)
W DecryptableStreamLocalUriFetcher: 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
W DecryptableStreamLocalUriFetcher: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W DecryptableStreamLocalUriFetcher: 	at libcore.io.Posix.open(Native Method)
W DecryptableStreamLocalUriFetcher: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W DecryptableStreamLocalUriFetcher: 	at libcore.io.IoBridge.open(IoBridge.java:438)
W DecryptableStreamLocalUriFetcher: ... 20 more
```

If someone is interested in looking into this, I've heard that sharing an image from Telegram to Signal fails 75% of the time.
