### ISSUE TITLE
Crash: "Content view not yet created"

### ISSUE THREAD

**Issue by wickedshimmy** [WhisperSystems/TextSecure#2915]
Occurred pretty coincident with a message being sent (SMS) but not sure it was related; the message went through. Let me know if you need more context from the log.

2.10.1, Android 4.4.4

**Comment by wickedshimmy** [comment]
````
E/AndroidRuntime(24245): FATAL EXCEPTION: main
E/AndroidRuntime(24245): Process: org.thoughtcrime.securesms, PID: 24245
E/AndroidRuntime(24245): java.lang.IllegalStateException: Content view not yet created
E/AndroidRuntime(24245): 	at android.support.v4.app.aj.ensureList(Unknown Source)
E/AndroidRuntime(24245): 	at android.support.v4.app.aj.getListView(Unknown Source)
E/AndroidRuntime(24245): 	at org.thoughtcrime.securesms.ConversationFragment.scrollToBottom(Unknown Source)
E/AndroidRuntime(24245): 	at org.thoughtcrime.securesms.ConversationActivity.sendComplete(Unknown Source)
E/AndroidRuntime(24245): 	at org.thoughtcrime.securesms.ConversationActivity.access$400(Unknown Source)
E/AndroidRuntime(24245): 	at org.thoughtcrime.securesms.ConversationActivity$15.onPostExecute(Unknown Source)
E/AndroidRuntime(24245): 	at org.thoughtcrime.securesms.ConversationActivity$15.onPostExecute(Unknown Source)
E/AndroidRuntime(24245): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime(24245): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(24245): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime(24245): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(24245): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(24245): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
E/AndroidRuntime(24245): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24245): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(24245): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(24245): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(24245): 	at dalvik.system.NativeStart.main(Native Method)
````

**Comment by agrajaghh** [comment]
same stacktrace in #2914

**Comment by moxie0** [comment]
What's weird is that person isn't reporting a crash...

**Comment by agrajaghh** [comment]
might have been old? btw, is it possible to include the time in the debuglog? sometimes it would be helpfull...

**Comment by mcginty** [comment]
This is probably a bug that's been around for a while. I'm guessing this happens when one sends then closes out of the conversation, so the AsyncTask completes after the view is no longer available. Thanks for the submission @wickedshimmy.

**Comment by volcano99** [comment]
If I'm "that person", yes, TextSecure did crash a while before I submitted the log in the other issue ( #2914 ). But it crashes very frequently, so I didn't notice. And it may be related to what mcginty says, I send messages and close conversations right away all the time.

**Comment by volcano99** [comment]
This just happened twice to me.
- I was texting (over push) with someone, sending and receiving several messages
- I got a text from someone else
- I sent a text in the conversation I was using, then quickly hit the back arrow, open the conversation with the new contact and ts crashed instantly
