### ISSUE TITLE
App Crashes while registering on a non secure custom http TextSecure server

### ISSUE THREAD

**Issue by supportreq** [WhisperSystems/TextSecure#2950]
Hi,

I am trying to connect TextSecure Client to my test server. I have changed the release.java file to http:// 

On registering the app crashes with following error:

Process: org.thoughtcrime.securesms, PID: 13873
    java.lang.ClassCastException: com.android.okhttp.internal.http.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.getConnection(Unknown Source)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(Unknown Source)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(Unknown Source)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.createAccount(Unknown Source)
            at org.whispersystems.textsecure.api.TextSecureAccountManager.requestSmsVerificationCode(Unknown Source)
            at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(Unknown Source)
            at org.thoughtcrime.securesms.service.RegistrationService.access$000(Unknown Source)
            at org.thoughtcrime.securesms.service.RegistrationService$1.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

Please advice..

**Comment by agrajaghh** [comment]
you already opened https://github.com/WhisperSystems/TextSecure-Server/issues/33 where they told you this is not a support forum, why do you open a similar question again?

**Comment by moxie0** [comment]
@supportreq stop it
