### ISSUE TITLE
CrashBrowser: RemoteServiceException

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2960]
`````
android.app.RemoteServiceException: Bad notification posted from package org.thoughtcrime.securesms: Couldn't expand RemoteViews for: StatusBarNotification(pkg=org.thoughtcrime.securesms user=UserHandle{0} id=4141 tag=null score=-20: Notification(pri=-2 contentView=org.thoughtcrime.securesms/0x1090065 vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null] 1 action))
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1372)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5146)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at dalvik.system.NativeStart.main(Native Method)
`````

**Comment by mcginty** [comment]
http://stackoverflow.com/questions/25317659/how-to-fix-android-app-remoteserviceexception-bad-notification-posted-from-pac

**Comment by mcginty** [comment]
I don't know if this is fixable. It looks like this happens when there's a pending notification created from an older version of the app that links to resource ids that changed after the update...

**Comment by mcginty** [comment]
According to some other SO posts, might be related to older APIs not supporting the "large icon" notification option, too. Is this limited to specific versions of Android on CrashBrowser?

**Comment by moxie0** [comment]
It looks like a variety of devices, most of them modern (4.0+).  Maybe it's the former?

**Comment by mcginty** [comment]
Sounds like the former then :confused:
