### ISSUE TITLE
'all images' view froze my phone

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#2961]
Here is the debug log, I was just scrolling down the list of images: https://gist.github.com/c4b8126902f42fe0eb57

**Comment by rhodey** [comment]
lots of out of memory errors in the log. seems that OOM kicked in once and then TS continued to try and load bitmaps, each time skipping ~50 frames, then finally culminating in a crash

```
E/AndroidRuntime(20408): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime(20408): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(20408): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
E/AndroidRuntime(20408): 	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime(20408): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime(20408): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime(20408): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime(20408): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/AndroidRuntime(20408): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime(20408): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime(20408): 	at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime(20408): Caused by: java.lang.OutOfMemoryError
E/AndroidRuntime(20408): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/AndroidRuntime(20408): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:621)
E/AndroidRuntime(20408): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(Unknown Source)
E/AndroidRuntime(20408): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(Unknown Source)
E/AndroidRuntime(20408): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(Unknown Source)
E/AndroidRuntime(20408): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(Unknown Source)
E/AndroidRuntime(20408): 	at org.thoughtcrime.securesms.util.BitmapUtil.createScaledBitmap(Unknown Source)
E/AndroidRuntime(20408): 	at org.thoughtcrime.securesms.MediaPreviewActivity$1.doInBackground(Unknown Source)
E/AndroidRuntime(20408): 	at org.thoughtcrime.securesms.MediaPreviewActivity$1.doInBackground(Unknown Source)
E/AndroidRuntime(20408): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/AndroidRuntime(20408): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime(20408): 	... 5 more
W/KeyCachingService(20408): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(20408): Incrementing activity count...
```
