### ISSUE TITLE
crash while sending pictures from gallery

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#2966]
https://gist.github.com/2a41f20c561465257de1

**Comment by agrajaghh** [comment]
````
E/AndroidRuntime( 3626): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime( 3626): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime( 3626): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4876)
E/AndroidRuntime( 3626): 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:948)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:292)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.widget.AbsListView.requestLayout(AbsListView.java:2126)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:292)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:292)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:292)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.requestLayout(View.java:15245)
E/AndroidRuntime( 3626): 	at android.view.View.setFlags(View.java:8400)
E/AndroidRuntime( 3626): 	at android.view.View.setVisibility(View.java:5590)
E/AndroidRuntime( 3626): 	at android.widget.ImageView.setVisibility(ImageView.java:1155)
E/AndroidRuntime( 3626): 	at org.thoughtcrime.securesms.components.ForegroundImageView.hide(Unknown Source)
E/AndroidRuntime( 3626): 	at org.thoughtcrime.securesms.ConversationItem$SlideDeckListener.onSuccess(Unknown Source)
E/AndroidRuntime( 3626): 	at org.thoughtcrime.securesms.ConversationItem$SlideDeckListener.onSuccess(Unknown Source)
E/AndroidRuntime( 3626): 	at org.thoughtcrime.securesms.util.ListenableFutureTask.callback(Unknown Source)
E/AndroidRuntime( 3626): 	at org.thoughtcrime.securesms.util.ListenableFutureTask.callback(Unknown Source)
E/AndroidRuntime( 3626): 	at org.thoughtcrime.securesms.util.ListenableFutureTask.done(Unknown Source)
E/AndroidRuntime( 3626): 	at java.util.concurrent.FutureTask$Sync.innerSet(FutureTask.java:252)
E/AndroidRuntime( 3626): 	at java.util.concurrent.FutureTask.set(FutureTask.java:112)
E/AndroidRuntime( 3626): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:310)
E/AndroidRuntime( 3626): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime( 3626): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 3626): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 3626): 	at java.lang.Thread.run(Thread.java:856)
````

**Comment by rhodey** [comment]
I believe this pull will fix / would have prevented this >> https://github.com/WhisperSystems/TextSecure/pull/2931

**Comment by mcginty** [comment]
Truth. Since the glide change is taking a while, just gonna throw this in for the mean time. Sorry @rhodey .

**Comment by rhodey** [comment]
no worries, just wanna squash bugs :)
