### ISSUE TITLE
NPE: ThumbnailView, tap preview icon when file not found

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3042]
encountered this while running an unmodified debug build of 27a5b7dd5c588abd677b6947c896df410d67a0f2

sequence of events were:
1) send a bunch of text messages
2) send a bunch of media messages
3) do the same while screwing around with airplane mode
4) attach image
5) image preview is an error icon (may have been `ic_action_warning_red` or `ic_missing_thumbnail_picture`, can't remember)
6) click on error image preview
7) crash

I then tried to reproduce by simply returning to the convo and reattaching the same image, crash again. Did this a few more times and once the image preview was entirely blank (but still took up the space it should), clicked on that too, crash. While in this crashable state I attempted to reproduce this using a different attachment, no crash. Thinking it may have had something to do with cache I tried another different image that definitely should not have been in cache, also no crash.

Eventually through some multi-step process I can't recall I was able to stop the error image from showing up for that one attachment and thus stop the crashing.

debug log >> https://gist.github.com/anonymous/266cafd4ee10f5f3e380

crash
```
E/AndroidRuntime(14933): FATAL EXCEPTION: main
E/AndroidRuntime(14933): Process: org.thoughtcrime.securesms.sushi, PID: 14933
E/AndroidRuntime(14933): java.lang.NullPointerException: Attempt to invoke interface method 'void org.thoughtcrime.securesms.components.ThumbnailView$ThumbnailClickListener.onClick(android.view.View, org.thoughtcrime.securesms.mms.Slide)' on a null object reference
E/AndroidRuntime(14933): 	at org.thoughtcrime.securesms.components.ThumbnailView$ThumbnailClickDispatcher.onClick(ThumbnailView.java:180)
E/AndroidRuntime(14933): 	at android.view.View.performClick(View.java:4780)
E/AndroidRuntime(14933): 	at android.view.View$PerformClick.run(View.java:19866)
E/AndroidRuntime(14933): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(14933): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(14933): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(14933): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(14933): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14933): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(14933): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(14933): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process (14933): Sending signal. PID: 14933 SIG: 9
```

some errors in a future that may be related to crash, comes after crash
```
W/PartDatabase( 8094): inserting part to mms 3
W/PartDatabase( 8094): Writing part data from URI
W/MessageSender( 8094): ws.com.google.android.mms.MmsException: java.io.FileNotFoundException: java.io.FileNotFoundException: Failed to find document file.
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.writePartData(PartDatabase.java:401)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.insertPart(PartDatabase.java:438)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.insertParts(PartDatabase.java:228)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.MmsDatabase.insertMediaMessage(MmsDatabase.java:755)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.MmsDatabase.insertMessageOutbox(MmsDatabase.java:724)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.sms.MessageSender.send(MessageSender.java:102)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.ConversationActivity$14.doInBackground(ConversationActivity.java:1044)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.ConversationActivity$14.doInBackground(ConversationActivity.java:1041)
W/MessageSender( 8094): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/MessageSender( 8094): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/MessageSender( 8094): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/MessageSender( 8094): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/MessageSender( 8094): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/MessageSender( 8094): 	at java.lang.Thread.run(Thread.java:818)
W/MessageSender( 8094): Caused by: java.io.FileNotFoundException: java.io.FileNotFoundException: Failed to find document file.
W/MessageSender( 8094): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
W/MessageSender( 8094): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
W/MessageSender( 8094): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
W/MessageSender( 8094): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
W/MessageSender( 8094): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.mms.PartAuthority.getPartStream(PartAuthority.java:44)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.writePartData(PartDatabase.java:395)
W/MessageSender( 8094): 	... 13 more
```

**Comment by rhodey** [comment]
update, definitely `ic_missing_thumbnail_picture`. steps to reproduce:

1) open a conversation
2) click add attachments
3) select an image that is synced to google drive
4) `ic_missing_thumbnail_picture` or white empty space will be shown in place of preview
5) click on `ic_missing_thumbnail_picture` or the white empty space
6) crash

![screenshot](http://i.imgur.com/4JmNBYO.jpg)

any of the images with the dumb drive icon will cause this crash the first few times they are selected, then eventually they will start to load correctly.
