### ISSUE TITLE
Glide Crash

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#3110]
`````
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:133)
at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:101)
at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:86)
at com.bumptech.glide.Glide.with(Glide.java:609)
at org.thoughtcrime.securesms.components.ThumbnailView.buildEncryptedPartGlideRequest(ThumbnailView.java:114)
at org.thoughtcrime.securesms.components.ThumbnailView.buildThumbnailGlideRequest(ThumbnailView.java:99)
at org.thoughtcrime.securesms.components.ThumbnailView.buildGlideRequest(ThumbnailView.java:80)
at org.thoughtcrime.securesms.components.ThumbnailView.setImageResource(ThumbnailView.java:60)
at org.thoughtcrime.securesms.components.ThumbnailView$SlideDeckListener$1.run(ThumbnailView.java:140)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5260)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`````

**Comment by nizamcs** [comment]
Hi,
Please check this.
http://crashes.to/s/a7c08d1ed9e
Happened today
