### ISSUE TITLE
Crash while trying to display picture message thumbnails

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3127]
1. Open a conversation that has picture messages
2. If necessary scroll up to find a picture message
3. Crash

https://gist.github.com/23d11c902a98491c22ab
```
E/AndroidRuntime(26145): FATAL EXCEPTION: main
E/AndroidRuntime(26145): Process: org.thoughtcrime.securesms, PID: 26145
E/AndroidRuntime(26145): java.lang.IllegalArgumentException: Unable to find GlideModule implementation
E/AndroidRuntime(26145): 	at com.bumptech.glide.module.ManifestParser.parseModule(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.module.ManifestParser.parse(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.Glide.get(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.RequestManager.<init>(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.RequestManager.<init>(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.manager.RequestManagerRetriever.get(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.manager.RequestManagerRetriever.get(Unknown Source)
E/AndroidRuntime(26145): 	at com.bumptech.glide.Glide.with(Unknown Source)
E/AndroidRuntime(26145): 	at org.thoughtcrime.securesms.components.ThumbnailView.buildEncryptedPartGlideRequest(Unknown Source)
E/AndroidRuntime(26145): 	at org.thoughtcrime.securesms.components.ThumbnailView.buildThumbnailGlideRequest(Unknown Source)
E/AndroidRuntime(26145): 	at org.thoughtcrime.securesms.components.ThumbnailView.buildGlideRequest(Unknown Source)
E/AndroidRuntime(26145): 	at org.thoughtcrime.securesms.components.ThumbnailView.setImageResource(Unknown Source)
E/AndroidRuntime(26145): 	at org.thoughtcrime.securesms.components.ThumbnailView$SlideDeckListener$1.run(Unknown Source)
E/AndroidRuntime(26145): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(26145): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(26145): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(26145): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(26145): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26145): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(26145): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(26145): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(26145): Caused by: java.lang.ClassNotFoundException: org.thoughtcrime.securesms.mms.TextSecureGlideModule
E/AndroidRuntime(26145): 	at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(26145): 	at java.lang.Class.forName(Class.java:309)
E/AndroidRuntime(26145): 	at java.lang.Class.forName(Class.java:273)
E/AndroidRuntime(26145): 	... 22 more
E/AndroidRuntime(26145): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.thoughtcrime.securesms.mms.TextSecureGlideModule" on path: DexPathList[[zip file "/data/app/org.thoughtcrime.securesms-1/base.apk"],nativeLibraryDirectories=[/data/app/org.thoughtcrime.securesms-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(26145): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(26145): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(26145): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(26145): 	... 25 more
E/AndroidRuntime(26145): 	Suppressed: java.lang.ClassNotFoundException: org.thoughtcrime.securesms.mms.TextSecureGlideModule
E/AndroidRuntime(26145): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(26145): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(26145): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(26145): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(26145): 		... 26 more
E/AndroidRuntime(26145): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

TS 2.14.0, Android 5.1

(Also sent too many crash reports through the app)

**Comment by mcginty** [comment]
@moxie0 might want to roll back if you see other crash reports with this in it. While the proguard rules seem like it should very obviously keep this class (as it's in org.thoughtcrime.securesms), did it get somehow stripped out?

**Comment by mcginty** [comment]
just signed a release build with my debug key, crashes for me too. it's an issue with the release build (and probably proguard)

**Comment by volcano99** [comment]
By the way, I lost all the messages I got while I couldn't open textsecure... I know I got some messages  because I got the notifications, but now that I managed to open it I can't see them :/
