### ISSUE TITLE
emoji panel stack trace

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#3166]
`````
E/AndroidRuntime( 2092): FATAL EXCEPTION: main
E/AndroidRuntime( 2092): java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams
E/AndroidRuntime( 2092): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:293)
E/AndroidRuntime( 2092): 	at android.view.View.layout(View.java:7175)
E/AndroidRuntime( 2092): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
E/AndroidRuntime( 2092): 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1243)
E/AndroidRuntime( 2092): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1049)
E/AndroidRuntime( 2092): 	at android.view.View.layout(View.java:7175)
E/AndroidRuntime( 2092): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
E/AndroidRuntime( 2092): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
E/AndroidRuntime( 2092): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
E/AndroidRuntime( 2092): 	at android.view.View.layout(View.java:7175)
E/AndroidRuntime( 2092): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
E/AndroidRuntime( 2092): 	at android.view.View.layout(View.java:7175)
E/AndroidRuntime( 2092): 	at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
E/AndroidRuntime( 2092): 	at android.view.View.layout(View.java:7175)
E/AndroidRuntime( 2092): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
E/AndroidRuntime( 2092): 	at android.view.View.layout(View.java:7175)
E/AndroidRuntime( 2092): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
E/AndroidRuntime( 2092): 	at android.view.View.layout(View.java:7175)
E/AndroidRuntime( 2092): 	at android.view.ViewRoot.performTraversals(ViewRoot.java:1140)
E/AndroidRuntime( 2092): 	at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
E/AndroidRuntime( 2092): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2092): 	at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 2092): 	at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime( 2092): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2092): 	at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 2092): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime( 2092): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 2092): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  114):   Force finishing activity org.thoughtcrime.securesms/.ConversationActivity

`````

**Comment by mcginty** [comment]
resolved in c7d2ed4f7d59268de308a1e462ce6cb4074bb55e
