### ISSUE TITLE
Crash on Conversation -> "All images"

### ISSUE THREAD

**Issue by unrulygnu** [WhisperSystems/TextSecure#3218]
Updated from master 14 May (ab8593d) to master 20 May (7ecc580) today.  TextSecure crashed when attempting to view "All images" on a conversation which contained images from before the update.  The crash seems to have been introduced in commit dc903e4.

**Device and software**

* Google Nexus 5 D820
* Android 5.1 LMY47I stock; no superuser
* TextSecure master 20 May (7ecc580), also master 18 May (dc903e4)

**Steps to reproduce**

1. Install Textsecure master 18 May (dc903e4) or later
2. Tap a conversation which contains images from before commit dc903e4 was installed
3. Tap the overflow menu, then "All images"
4. Observe the app come crashing down

**Log: CRASH `git checkout 7ecc580` (latest master)**

    05-21 16:53:56.119  15878-15878/org.thoughtcrime.securesms W/KeyCachingService﹕ onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
    05-21 16:53:56.120  15878-15878/org.thoughtcrime.securesms W/KeyCachingService﹕ Decrementing activity count...
    05-21 16:53:56.120  15878-15878/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Active Count: 0
    05-21 16:53:56.125  15878-15878/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity﹕ routeApplicationState(), state: 0
    05-21 16:53:56.132  15878-15878/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity﹕ initializeClearKeyReceiver()
    05-21 16:53:56.152  15878-15878/org.thoughtcrime.securesms W/KeyCachingService﹕ onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
    05-21 16:53:56.152  15878-15878/org.thoughtcrime.securesms W/KeyCachingService﹕ Incrementing activity count...
    05-21 16:53:56.153  15878-15878/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Active Count: 1
    05-21 16:53:56.189  15878-15878/org.thoughtcrime.securesms E/RecyclerView﹕ No adapter attached; skipping layout
    05-21 16:53:56.189  15878-15878/org.thoughtcrime.securesms W/MediaOverviewActivity﹕ onLoadFinished()
    05-21 16:53:56.196  15878-15878/org.thoughtcrime.securesms D/AndroidRuntime﹕ Shutting down VM
    05-21 16:53:56.197  15878-15878/org.thoughtcrime.securesms E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: org.thoughtcrime.securesms, PID: 15878
        java.lang.IllegalArgumentException: column 'cid' does not exist
                at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:303)
                at org.thoughtcrime.securesms.database.PartDatabase$ImageRecord.from(PartDatabase.java:554)
                at org.thoughtcrime.securesms.ImageMediaAdapter.onBindViewHolder(ImageMediaAdapter.java:69)
                at org.thoughtcrime.securesms.ImageMediaAdapter.onBindViewHolder(ImageMediaAdapter.java:41)
                at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.onBindViewHolder(CursorRecyclerViewAdapter.java:103)
                at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
                at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:356)
                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
                at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:151)
                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                at android.view.Choreographer.doFrame(Choreographer.java:550)
                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                at android.os.Handler.handleCallback(Handler.java:739)
                at android.os.Handler.dispatchMessage(Handler.java:95)
                at android.os.Looper.loop(Looper.java:135)
                at android.app.ActivityThread.main(ActivityThread.java:5254)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            
**Log: CRASH `git checkout dc903e4`**

    05-21 16:43:05.952    6206-6206/org.thoughtcrime.securesms W/KeyCachingService﹕ onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
    05-21 16:43:05.952    6206-6206/org.thoughtcrime.securesms W/KeyCachingService﹕ Decrementing activity count...
    05-21 16:43:05.952    6206-6206/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Active Count: 0
    05-21 16:43:05.959    6206-6206/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity﹕ routeApplicationState(), state: 0
    05-21 16:43:05.964    6206-6206/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity﹕ initializeClearKeyReceiver()
    05-21 16:43:05.986    6206-6206/org.thoughtcrime.securesms W/KeyCachingService﹕ onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
    05-21 16:43:05.986    6206-6206/org.thoughtcrime.securesms W/KeyCachingService﹕ Incrementing activity count...
    05-21 16:43:05.986    6206-6206/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Active Count: 1
    05-21 16:43:06.017    6206-6206/org.thoughtcrime.securesms E/RecyclerView﹕ No adapter attached; skipping layout
    05-21 16:43:06.017    6206-6206/org.thoughtcrime.securesms W/MediaOverviewActivity﹕ onLoadFinished()
    05-21 16:43:06.025    6206-6206/org.thoughtcrime.securesms D/AndroidRuntime﹕ Shutting down VM
    05-21 16:43:06.026    6206-6206/org.thoughtcrime.securesms E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: org.thoughtcrime.securesms, PID: 6206
        java.lang.IllegalArgumentException: column 'cid' does not exist
                at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:303)
                at org.thoughtcrime.securesms.database.PartDatabase$ImageRecord.from(PartDatabase.java:554)
                at org.thoughtcrime.securesms.ImageMediaAdapter.onBindViewHolder(ImageMediaAdapter.java:69)
                at org.thoughtcrime.securesms.ImageMediaAdapter.onBindViewHolder(ImageMediaAdapter.java:41)
                at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.onBindViewHolder(CursorRecyclerViewAdapter.java:103)
                at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
                at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:356)
                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
                at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:151)
                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                at android.view.View.layout(View.java:15671)
                at android.view.ViewGroup.layout(ViewGroup.java:5038)
                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                at android.view.Choreographer.doFrame(Choreographer.java:550)
                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                at android.os.Handler.handleCallback(Handler.java:739)
                at android.os.Handler.dispatchMessage(Handler.java:95)
                at android.os.Looper.loop(Looper.java:135)
                at android.app.ActivityThread.main(ActivityThread.java:5254)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**LOG: OK `git checkout 0829852` (commit prior to dc903e4)**
 
    05-21 17:06:06.905  21189-21189/org.thoughtcrime.securesms W/KeyCachingService﹕ onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
    05-21 17:06:06.906  21189-21189/org.thoughtcrime.securesms W/KeyCachingService﹕ Decrementing activity count...
    05-21 17:06:06.906  21189-21189/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Active Count: 0
    05-21 17:06:06.909  21189-21189/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity﹕ routeApplicationState(), state: 0
    05-21 17:06:06.914  21189-21189/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity﹕ initializeClearKeyReceiver()
    05-21 17:06:06.927  21189-21189/org.thoughtcrime.securesms W/KeyCachingService﹕ onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
    05-21 17:06:06.927  21189-21189/org.thoughtcrime.securesms W/KeyCachingService﹕ Incrementing activity count...
    05-21 17:06:06.928  21189-21189/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Active Count: 1
    05-21 17:06:06.928  21189-21189/org.thoughtcrime.securesms W/MediaOverviewActivity﹕ onLoadFinished()
    05-21 17:06:07.037  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.039  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.040  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.041  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.050  21189-27891/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.066  21189-27891/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.068  21189-27892/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.069  21189-27892/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.125  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.126  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/part-XXXX.mms
    05-21 17:06:07.136  21189-27892/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.142  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.142  21189-27891/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.146  21189-27892/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/part-XXXX.mms
    05-21 17:06:07.147  21189-27891/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/part-XXXX.mms
    05-21 17:06:07.147  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.156  21189-21204/org.thoughtcrime.securesms I/art﹕ Background sticky concurrent mark sweep GC freed 47811(2MB) AllocSpace objects, 24(2MB) LOS objects, 0% free, 27MB/27MB, paused 1.998ms total 106.709ms
    05-21 17:06:07.191  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.201  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.203  21189-27891/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.205  21189-27892/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.210  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.211  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/part-XXXX.mms
    05-21 17:06:07.220  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.224  21189-27890/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.239  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.240  21189-27892/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.243  21189-27891/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/part-XXXX.mms
    05-21 17:06:07.244  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/partXXXX.mms
    05-21 17:06:07.257  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ getThumbnailStream(XX)
    05-21 17:06:07.257  21189-27889/org.thoughtcrime.securesms W/PartDatabase﹕ Getting part at: /data/data/org.thoughtcrime.securesms/app_parts/part-XXXX.mms

**Comment by unrulygnu** [comment]
In commit dc903e4, a column (`CONTENT_ID`) was added to the `ImageRecord` returned by `from()`:

**PartDatabase.java**

        public static ImageRecord from(Cursor cursor) {
          return new ImageRecord(cursor.getLong(cursor.getColumnIndexOrThrow(ID)),
                                 Util.toIsoBytes(cursor.getString(cursor.getColumnIndexOrThrow(CONTENT_ID))), // Line 554, referenced in the crash log
                                 cursor.getString(cursor.getColumnIndexOrThrow(CONTENT_TYPE)),
                                 cursor.getString(cursor.getColumnIndexOrThrow(MmsDatabase.ADDRESS)),
                                 cursor.getLong(cursor.getColumnIndexOrThrow(MmsDatabase.NORMALIZED_DATE_RECEIVED)) * 1000);
        }
        
But `IMAGES_QUERY` doesn't include the new column:

**PartDatabase.java**

      private final static String IMAGES_QUERY = "SELECT " + TABLE_NAME + "." + ID + ", "
                                                           + TABLE_NAME + "." + CONTENT_TYPE + ", "
                                                           + TABLE_NAME + "." + ASPECT_RATIO + ", "
                                                           + MmsDatabase.TABLE_NAME + "." + MmsDatabase.NORMALIZED_DATE_RECEIVED + ", "
                                                           + MmsDatabase.TABLE_NAME + "." + MmsDatabase.ADDRESS + " "
                                               + "FROM " + TABLE_NAME + " LEFT JOIN " + MmsDatabase.TABLE_NAME
                                                                      + " ON " + TABLE_NAME + "." + MMS_ID + " = " + MmsDatabase.TABLE_NAME + "." + MmsDatabase.ID + " "
                                               + "WHERE " + MMS_ID + " IN (SELECT " + MmsSmsColumns.ID
                                                                       + " FROM " + MmsDatabase.TABLE_NAME
                                                                       + " WHERE " + MmsDatabase.THREAD_ID + " = ?) AND "
                                                          + CONTENT_TYPE + " LIKE 'image/%' "
                                               + "ORDER BY " + TABLE_NAME + "." + ID + " DESC";

And the field assignment for `contentId` is missing in the `ImageRecord` constructor:

**PartDatabase.java**

        private ImageRecord(long partId, byte[] contentId, String contentType, String address, long date) {
          this.partId      = partId;
          this.contentType = contentType;
          this.address     = address;
          this.date        = date;
        }


Fixing the above allows `contentId` to start flowing; HOWEVER, I have rows in my `part` table with empty `cid` columns, which crash the app on `Util.toIsoBytes` on the original crash line:

    Util.toIsoBytes(cursor.getString(cursor.getColumnIndexOrThrow(CONTENT_ID))),

Since I'm new to the codebase, I'm not sure if handling the null here is going to just cause more problems which I won't be aware of later, so I'm holding off on a PR for now.

**Comment by unrulygnu** [comment]
Also seems related to #3210

**Comment by unrulygnu** [comment]
I made a quick change to handle empty `cid` columns:

        public static ImageRecord from(Cursor cursor) {
          final String contentId = cursor.getString(cursor.getColumnIndexOrThrow(CONTENT_ID));
    
          return new ImageRecord(cursor.getLong(cursor.getColumnIndexOrThrow(ID)),
                                 Util.toIsoBytes(contentId == null ? "" : contentId),
                                 cursor.getString(cursor.getColumnIndexOrThrow(CONTENT_TYPE)),
                                 cursor.getString(cursor.getColumnIndexOrThrow(MmsDatabase.ADDRESS)),
                                 cursor.getLong(cursor.getColumnIndexOrThrow(MmsDatabase.NORMALIZED_DATE_RECEIVED)) * 1000);
        }

Oh, dear:

![redacted](https://cloud.githubusercontent.com/assets/11031903/7746040/66c13f2c-ffea-11e4-97c7-6e12cfc6282d.png)

And lots of these in the log:

    05-21 18:47:14.359    2271-3211/org.thoughtcrime.securesms W/DecryptableStreamLocalUriFetcher﹕ java.io.FileNotFoundException: No part for id: 73
                at org.thoughtcrime.securesms.database.PartDatabase.getDataStream(PartDatabase.java:368)
                at org.thoughtcrime.securesms.database.PartDatabase.getThumbnailStream(PartDatabase.java:412)
                at org.thoughtcrime.securesms.mms.PartAuthority.getPartStream(PartAuthority.java:48)
                at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:30)
                at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:16)
                at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
                at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
                at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
                at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:818)
                at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:52)
