### ISSUE TITLE
crash on open of all images view

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3221]
https://gist.github.com/anonymous/69ac998ca39cab03779d

```
E/AndroidRuntime(19018): FATAL EXCEPTION: main
E/AndroidRuntime(19018): Process: org.thoughtcrime.securesms.sushi, PID: 19018
E/AndroidRuntime(19018): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(19018): 	at org.thoughtcrime.securesms.util.Hex.toStringCondensed(Hex.java:50)
E/AndroidRuntime(19018): 	at org.thoughtcrime.securesms.mms.PartAuthority.getPartUri(PartAuthority.java:63)
E/AndroidRuntime(19018): 	at org.thoughtcrime.securesms.database.PartDatabase$ImageRecord.getUri(PartDatabase.java:579)
E/AndroidRuntime(19018): 	at org.thoughtcrime.securesms.ImageMediaAdapter.onBindViewHolder(ImageMediaAdapter.java:73)
E/AndroidRuntime(19018): 	at org.thoughtcrime.securesms.ImageMediaAdapter.onBindViewHolder(ImageMediaAdapter.java:41)
E/AndroidRuntime(19018): 	at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.onBindViewHolder(CursorRecyclerViewAdapter.java:103)
E/AndroidRuntime(19018): 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
E/AndroidRuntime(19018): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
E/AndroidRuntime(19018): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
E/AndroidRuntime(19018): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
E/AndroidRuntime(19018): 	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:356)
E/AndroidRuntime(19018): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
E/AndroidRuntime(19018): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
E/AndroidRuntime(19018): 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:151)
E/AndroidRuntime(19018): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
E/AndroidRuntime(19018): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
E/AndroidRuntime(19018): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(19018): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(19018): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
E/AndroidRuntime(19018): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(19018): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(19018): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(19018): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(19018): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(19018): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(19018): 	at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
E/AndroidRuntime(19018): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(19018): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(19018): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(19018): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(19018): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(19018): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(19018): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(19018): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(19018): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(19018): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(19018): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(19018): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(19018): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(19018): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(19018): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(19018): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
E/AndroidRuntime(19018): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
E/AndroidRuntime(19018): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(19018): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime(19018): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(19018): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(19018): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(19018): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(19018): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(19018): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(19018): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19018): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(19018): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19018): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19018): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(19018): 	at com.
I/Process (19018): Sending signal. PID: 19018 SIG: 9
I/art     (20887): Late-enabling -Xcheck:jni
```

**Comment by mcginty** [comment]
should be fixed now
