### ISSUE TITLE
picture not delivered

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/TextSecure#3250]
I repeatedly tried to send a picture with text to a certain number, but get a "not delivered" information after a while. Sending images without text to another number succeeded (but the image was never displayed, issue #3248).

My internet connection is of very low bandwidth and high latency.

https://gist.github.com/e839de9e03504426718e

**Comment by mcginty** [comment]
relevant exceptions

```
W/PushServiceSocket( 4624): Got attachment content location: ...
W/OkHttpClientWrapper( 4624): java.io.EOFException
W/OkHttpClientWrapper( 4624): 	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
W/OkHttpClientWrapper( 4624): 	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
W/OkHttpClientWrapper( 4624): 	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:130)
W/OkHttpClientWrapper( 4624): 	at com.squareup.okhttp.internal.ws.WebSocketReader.readUntilNonControlFrame(WebSocketReader.java:119)
W/OkHttpClientWrapper( 4624): 	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:94)
W/OkHttpClientWrapper( 4624): 	at com.squareup.okhttp.internal.ws.WebSocket$ReaderRunnable.execute(WebSocket.java:355)
W/OkHttpClientWrapper( 4624): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
W/OkHttpClientWrapper( 4624): 	at java.lang.Thread.run(Thread.java:818)
W/WebSocketConnection( 4624): onClose()...
W/OkHttpClientWrapper( 4624): Calling disconnect()...
```

```
W/PushMediaSendJob( 4624): java.io.IOException: Bad response: 400 Bad Request
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:424)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:326)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:285)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:269)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:154)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:119)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:118)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:66)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushMediaSendJob( 4624): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/PushMediaSendJob( 4624): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/JobConsumer( 4624): org.thoughtcrime.securesms.transport.RetryLaterException: java.io.IOException: Bad response: 400 Bad Request
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:124)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:66)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/JobConsumer( 4624): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/JobConsumer( 4624): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/JobConsumer( 4624): Caused by: java.io.IOException: Bad response: 400 Bad Request
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:424)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:326)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:285)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:269)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:154)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:119)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:118)
W/JobConsumer( 4624): 	... 5 more
```

```
W/OkHttpClientWrapper( 4624): onMessage: BINARY
W/WebSocketConnection( 4624): WSC onMessage()
W/WebSocketConnection( 4624): Message Type: 2
W/PushMediaSendJob( 4624): javax.net.ssl.SSLException: Write error: ssl=0xb95ed160: I/O error during system call, Connection reset by peer
W/PushMediaSendJob( 4624): 	at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
W/PushMediaSendJob( 4624): 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:765)
W/PushMediaSendJob( 4624): 	at com.android.okio.Okio$1.write(Okio.java:70)
W/PushMediaSendJob( 4624): 	at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
W/PushMediaSendJob( 4624): 	at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
W/PushMediaSendJob( 4624): 	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
W/PushMediaSendJob( 4624): 	at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
W/PushMediaSendJob( 4624): 	at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
W/PushMediaSendJob( 4624): 	at java.io.OutputStream.write(OutputStream.java:82)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.crypto.AttachmentCipherOutputStream.write(AttachmentCipherOutputStream.java:74)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.internal.util.Util.copy(Util.java:105)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:420)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:326)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:285)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:269)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:154)
W/PushMediaSendJob( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:119)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:118)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:66)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/PushMediaSendJob( 4624): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushMediaSendJob( 4624): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/PushMediaSendJob( 4624): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/JobConsumer( 4624): org.thoughtcrime.securesms.transport.RetryLaterException: javax.net.ssl.SSLException: Write error: ssl=0xb95ed160: I/O error during system call, Connection reset by peer
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:124)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:66)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/JobConsumer( 4624): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/JobConsumer( 4624): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/JobConsumer( 4624): Caused by: javax.net.ssl.SSLException: Write error: ssl=0xb95ed160: I/O error during system call, Connection reset by peer
W/JobConsumer( 4624): 	at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
W/JobConsumer( 4624): 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:765)
W/JobConsumer( 4624): 	at com.android.okio.Okio$1.write(Okio.java:70)
W/JobConsumer( 4624): 	at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
W/JobConsumer( 4624): 	at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
W/JobConsumer( 4624): 	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
W/JobConsumer( 4624): 	at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
W/JobConsumer( 4624): 	at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
W/JobConsumer( 4624): 	at java.io.OutputStream.write(OutputStream.java:82)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.crypto.AttachmentCipherOutputStream.write(AttachmentCipherOutputStream.java:74)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.internal.util.Util.copy(Util.java:105)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:420)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:326)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:285)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:269)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:154)
W/JobConsumer( 4624): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:119)
W/JobConsumer( 4624): 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:118)
W/JobConsumer( 4624): 	... 5 more
```

**Comment by moxie0** [comment]
Looks like a network error while communicating with S3 to me.  We retry a few times, but if the network can't get the data up, we eventually fail.
