### ISSUE TITLE
Force close upon sending push message

### ISSUE THREAD

**Issue by 5boro** [WhisperSystems/TextSecure#3276]
Upon pressing the send button TextSecure closed and relaunched with the text sent.
Nothing special about the content of the massage, only text, but the contact was the one mentioned in #3275 

Log : https://gist.github.com/anonymous/6091dceb7dfb16ecabc7

**Comment by moxie0** [comment]
The exception:

`````
E/AndroidRuntime(30012): FATAL EXCEPTION: main
E/AndroidRuntime(30012): Process: org.thoughtcrime.securesms, PID: 30012
E/AndroidRuntime(30012): java.lang.RuntimeException: Unable to instantiate application org.thoughtcrime.securesms.ApplicationContext: java.lang.IllegalStateException: Unable to get package info for org.thoughtcrime.securesms; is package not installed?
E/AndroidRuntime(30012): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:581)
E/AndroidRuntime(30012): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4752)
E/AndroidRuntime(30012): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/AndroidRuntime(30012): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
E/AndroidRuntime(30012): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30012): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(30012): 	at android.app.ActivityThread.main(ActivityThread.java:5499)
E/AndroidRuntime(30012): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30012): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(30012): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime(30012): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
E/AndroidRuntime(30012): Caused by: java.lang.IllegalStateException: Unable to get package info for org.thoughtcrime.securesms; is package not installed?
E/AndroidRuntime(30012): 	at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:414)
E/AndroidRuntime(30012): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:560)
E/AndroidRuntime(30012): 	... 10 more
E/AndroidRuntime( 6477): FATAL EXCEPTION: main
E/AndroidRuntime( 6477): Process: org.thoughtcrime.securesms, PID: 6477
E/AndroidRuntime( 6477): java.lang.RuntimeException: Unable to instantiate application org.thoughtcrime.securesms.ApplicationContext: java.lang.IllegalStateException: Unable to get package info for org.thoughtcrime.securesms; is package not installed?
E/AndroidRuntime( 6477): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:581)
E/AndroidRuntime( 6477): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4752)
E/AndroidRuntime( 6477): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/AndroidRuntime( 6477): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
E/AndroidRuntime( 6477): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6477): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6477): 	at android.app.ActivityThread.main(ActivityThread.java:5499)
E/AndroidRuntime( 6477): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6477): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6477): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime( 6477): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
E/AndroidRuntime( 6477): Caused by: java.lang.IllegalStateException: Unable to get package info for org.thoughtcrime.securesms; is package not installed?
E/AndroidRuntime( 6477): 	at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:414)
E/AndroidRuntime( 6477): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:560)
E/AndroidRuntime( 6477): 	... 10 more
--------- beginning of system
`````

The crash looks like an Android OS bug.  Nothing we can do if it can't find the installed APK.
