### ISSUE TITLE
android.view.InflateException: when opening message details view

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3326]
tested on 5fe7c687f36ebd7a2f800d07448735c47407d487 [debug log](https://gist.github.com/anonymous/546db0e2001f2b015cac)

1) send a TextSecure message
2) long press
3) view message details
4) crash

```
--------- beginning of crash
E/AndroidRuntime(12009): FATAL EXCEPTION: main
E/AndroidRuntime(12009): Process: org.thoughtcrime.securesms.sushi, PID: 12009
E/AndroidRuntime(12009): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms.sushi/org.thoughtcrime.securesms.MessageDetailsActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class <unknown>
E/AndroidRuntime(12009): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime(12009): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime(12009): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(12009): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime(12009): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12009): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(12009): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(12009): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12009): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12009): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(12009): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(12009): Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class <unknown>
E/AndroidRuntime(12009): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime(12009): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
E/AndroidRuntime(12009): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
E/AndroidRuntime(12009): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
E/AndroidRuntime(12009): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime(12009): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime(12009): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime(12009): 	at org.thoughtcrime.securesms.MessageDetailsActivity.initializeResources(MessageDetailsActivity.java:112)
E/AndroidRuntime(12009): 	at org.thoughtcrime.securesms.MessageDetailsActivity.onCreate(MessageDetailsActivity.java:97)
E/AndroidRuntime(12009): 	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:46)
E/AndroidRuntime(12009): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(12009): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(12009): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime(12009): 	... 10 more
E/AndroidRuntime(12009): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(12009): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime(12009): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime(12009): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime(12009): 	... 22 more
E/AndroidRuntime(12009): Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 13
E/AndroidRuntime(12009): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:747)
E/AndroidRuntime(12009): 	at android.view.View.<init>(View.java:3737)
E/AndroidRuntime(12009): 	at android.view.ViewGroup.<init>(ViewGroup.java:497)
E/AndroidRuntime(12009): 	at android.widget.FrameLayout.<init>(FrameLayout.java:115)
E/AndroidRuntime(12009): 	at android.widget.FrameLayout.<init>(FrameLayout.java:111)
E/AndroidRuntime(12009): 	at android.widget.FrameLayout.<init>(FrameLayout.java:107)
E/AndroidRuntime(12009): 	... 25 more
I/Process (12009): Sending signal. PID: 12009 SIG: 9
```

**Comment by rhodey** [comment]
fixed by 12255ed453058d1100d068815018d556c8ab224f
