### ISSUE TITLE
crash on select image for new group

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3335]
1) tap "New group"
2) tap the placeholder group image icon
3) select an image of a duck being plucked (referenced below)
4) crash

[debug log](https://gist.github.com/anonymous/16bb1ad0711feaebd117), note much of this debug log is full of unrelated crashes from previously submitted bug reports, relevant section copied below.

```
D/AndroidRuntime( 4853): Shutting down VM
E/AndroidRuntime( 4853): FATAL EXCEPTION: main
E/AndroidRuntime( 4853): Process: org.thoughtcrime.securesms.sushi, PID: 4853
E/AndroidRuntime( 4853): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms.sushi/com.soundcloud.android.crop.CropImageActivity}: java.lang.IllegalArgumentException: Unknown column requested: _data
E/AndroidRuntime( 4853): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime( 4853): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime( 4853): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 4853): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 4853): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4853): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4853): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 4853): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4853): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4853): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 4853): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 4853): Caused by: java.lang.IllegalArgumentException: Unknown column requested: _data
E/AndroidRuntime( 4853): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
E/AndroidRuntime( 4853): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
E/AndroidRuntime( 4853): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
E/AndroidRuntime( 4853): 	at android.content.ContentResolver.query(ContentResolver.java:478)
E/AndroidRuntime( 4853): 	at android.content.ContentResolver.query(ContentResolver.java:422)
E/AndroidRuntime( 4853): 	at com.soundcloud.android.crop.CropUtil.getFromMediaUri(CropUtil.java:95)
E/AndroidRuntime( 4853): 	at com.soundcloud.android.crop.CropImageActivity.setupFromIntent(CropImageActivity.java:126)
E/AndroidRuntime( 4853): 	at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
E/AndroidRuntime( 4853): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 4853): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 4853): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 4853): 	... 10 more
```

the exact image on my device which causes this behavior
![duck](http://i.ytimg.com/vi/_sDvpQWbZlc/maxresdefault.jpg)

**Comment by rhodey** [comment]
appears this is actually another case of #3085, I don't see any FNFE in the log but everything else matches up, also this image was synced with google drive (accidentally) so +1 to that being a cause of weirdness again.
