### ISSUE TITLE
Unable to send images; does not SEEM to be memory

### ISSUE THREAD

**Issue by Grunthos** [WhisperSystems/TextSecure#3361]
I don't seem to be able to send images (Android 4.0.3). A section of the log is below (I can send more if relevant):

(log edited out in favor of @5boro's formatted one below - @mcginty)

**Comment by 5boro** [comment]
```
6-07 12:13:28.772 I/ProxyService(2638): Request 24 CONNECT whispersystems-textsecure-attachments.s3.amazonaws.com:443 HTTP/1.1
06-07 12:13:28.772 V/main. (2638): invoking handler: https
06-07 12:13:28.772 I/https. (2638): SSL connection to whispersystems-textsecure-attachments.s3.amazonaws.com:443
06-07 12:13:28.782 W/WindowManager(240): Failure taking screenshot for (180x320) to layer 21020
06-07 12:13:28.792 D/ActivityManager(240): Config after re-evaluted by window manager: null
06-07 12:13:28.792 D/ConnectivityService(240): onUidRulesChanged(uid=10204, uidRules=0)
06-07 12:13:28.802 W/KeyCachingService(14022): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
06-07 12:13:28.802 W/KeyCachingService(14022): Decrementing activity count...
06-07 12:13:28.802 W/MessageRetrievalService(14022): Active Count: 0
06-07 12:13:28.822 D/TileRenderer(12773): glEndTilingQCOM: 0x502
06-07 12:13:28.872 D/TileRenderer(12773): glEndTilingQCOM: 0x502
06-07 12:13:28.942 E/memalloc(121): /dev/pmem: No more pmem available
06-07 12:13:28.942 W/memalloc(121): Falling back to ashmem
06-07 12:13:28.972 D/memalloc(13777): map_buffer: Successfully mapped 2088960 bytes
06-07 12:13:29.002 V/WindowManager(240): onProposedRotationChanged, rotation changed to 0
06-07 12:13:29.012 V/WindowManager(240): Starting animation in AppWindowToken{422f3948 token=Token{416b0f68 ActivityRecord{40db60e8 org.thoughtcrime.securesms/.MessageDetailsActivity}}} @ 48238811
06-07 12:13:29.012 V/WindowManager(240): Finished animation in AppWindowToken{422f3948 token=Token{416b0f68 ActivityRecord{40db60e8 org.thoughtcrime.securesms/.MessageDetailsActivity}}} @ 48238811
06-07 12:13:29.022 D/OpenGLRenderer(14022): Flushing caches (mode 0)
06-07 12:13:29.022 V/WindowManager(240): Starting animation in AppWindowToken{423d2880 token=Token{41af1568 ActivityRecord{41b7dfa0 com.nolanlawson.logcat/.LogcatActivity}}} @ 48238811
06-07 12:13:29.082 E/memalloc(121): /dev/pmem: No more pmem available
06-07 12:13:29.082 W/memalloc(121): Falling back to ashmem
06-07 12:13:29.092 D/OpenGLRenderer(12773): Flushing caches (mode 0)
06-07 12:13:29.102 D/memalloc(12773): /dev/pmem: Unmapping buffer base:0x58b7b000 size:10166272 offset:8077312
06-07 12:13:29.112 D/memalloc(121): /dev/pmem: Freeing buffer base:0x4288c000 size:2088960 offset:8077312 fd:42
06-07 12:13:29.112 D/memalloc(121): free_buffer:Freeing buffer size=2088960 base=0x4332a000 fd=51 PID=121
06-07 12:13:29.132 V/PhoneStatusBar(12773): setLightsOn(true)
06-07 12:13:29.132 D/memalloc(121): free_buffer:Freeing buffer size=2088960 base=0x43715000 fd=54 PID=121
06-07 12:13:29.142 D/memalloc(13777): map_buffer: Successfully mapped 2088960 bytes
06-07 12:13:29.162 D/MP-Decision(792): UP Nw:2.700000 Tw:180 rq:7.200000 seq:199
06-07 12:13:29.212 W/PushMediaSendJob(14022): java.net.SocketException: Socket is closed
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:262)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:273)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:441)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:164)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:414)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:326)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:304)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:288)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:165)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:120)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:118)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:66)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
06-07 12:13:29.212 W/PushMediaSendJob(14022): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
06-07 12:13:29.232 W/JobConsumer(14022): org.thoughtcrime.securesms.transport.RetryLaterException: java.net.SocketException: Socket is closed
06-07 12:13:29.232 W/JobConsumer(14022): at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:124)
06-07 12:13:29.232 W/JobConsumer(14022): at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onSend(PushMediaSendJob.java:66)
06-07 12:13:29.232 W/JobConsumer(14022): at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
06-07 12:13:29.232 W/JobConsumer(14022): at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
06-07 12:13:29.232 W/JobConsumer(14022): Caused by: java.net.SocketException: Socket is closed
06-07 12:13:29.232 W/JobConsumer(14022): at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:262)
06-07 12:13:29.232 W/JobConsumer(14022): at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:273)
06-07 12:13:29.232 W/JobConsumer(14022): at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257)
06-07 12:13:29.232 W/JobConsumer(14022): at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
06-07 12:13:29.232 W/JobConsumer(14022): at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
06-07 12:13:29.232 W/JobConsumer(14022): at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:441)
06-07 12:13:29.232 W/JobConsumer(14022): at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
06-07 12:13:29.232 W/JobConsumer(14022): at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
06-07 12:13:29.232 W/JobConsumer(14022): at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
06-07 12:13:29.232 W/JobConsumer(14022): at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:164)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.textsecure.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:414)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:326)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointer(TextSecureMessageSender.java:304)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.createAttachmentPointers(TextSecureMessageSender.java:288)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.createMessageContent(TextSecureMessageSender.java:165)
06-07 12:13:29.232 W/JobConsumer(14022): at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:120)
06-07 12:13:29.232 W/JobConsumer(14022): at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:118)
06-07 12:13:29.232 W/JobConsumer(14022): ... 5 more
06-07 12:13:29.242 D/memalloc(14022): /dev/pmem: Unmapping buffer base:0x549ef000 size:4177920 offset:2088960
06-07 12:13:29.242 D/memalloc(121): free_buffer:Freeing buffer size=2088960 base=0x44529000 fd=71 PID=121
06-07 12:13:29.252 D/memalloc(121): /dev/pmem: Freeing buffer base:0x422d6000 size:2088960 offset:2088960 fd:29
06-07 12:13:29.252 W/InputManagerService(240): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@42580690 (uid=10203 pid=14022)
06-07 12:13:29.262 D/memalloc(121): free_buffer:Freeing buffer size=2088960 base=0x447e4000 fd=74 PID=121
06-07 12:13:29.332 D/WifiStateMachine(240): fetchRssiAndLinkSpeedNative send RSSIChange intent, SameSignalLevelCount =1
06-07 12:13:29.382 D/MediaPlayer(240): setDataSource(Context context, content://settings/system/notification_sound, Map headers) in
06-07 12:13:29.392 V/WindowManager(240): onProposedRotationChanged, rotation changed to 0
06-07 12:13:29.392 D/lights (240): [LedInfo] write attr ok name=/sys/class/leds/amber/brightness string=0,len=1
06-07 12:13:29.392 D/lights (240): [LedInfo] write attr ok name=/sys/class/leds/amber/blink string=0,len=1
06-07 12:13:29.392 D/lights (240): [LedInfo] write attr ok name=/sys/class/leds/amber/off_timer string=0 0,len=3
06-07 12:13:29.392 D/lights (240): [LedInfo] write attr ok name=/sys/class/leds/green/brightness string=1,len=1
06-07 12:13:29.392 D/lights (240): [LedInfo] write attr ok name=/sys/class/leds/green/blink string=3,len=1
06-07 12:13:29.392 D/lights (240): [LedInfo] write attr ok name=/sys/class/leds/green/off_timer string=5 0,len=3
```

**Comment by Grunthos** [comment]
Maybe I lied. I just saw this:

06-07 12:13:29.082 E/memalloc(121): /dev/pmem: No more pmem available

**Comment by moxie0** [comment]
This is just a network failure.  Looks like you're using a proxy or something?

**Comment by Grunthos** [comment]
No proxy I am aware of, and yes it looks like a network failure, except:

- it always happens on images (every time, no matter how small)
- it never happens on text

This makes me think it's an app-related network issue.

Unless of course images use a different protocol than text when send peer-to-peer.

**Comment by moxie0** [comment]
`````
6-07 12:13:28.772 I/ProxyService(2638): Request 24 CONNECT whispersystems-textsecure-attachments.s3.amazonaws.com:443 HTTP/1.1
`````
Looks pretty definitely like something going on with your OS, or some weird firewall something something you have.

**Comment by Grunthos** [comment]
Can you explain why that is? Should I assume that "whispersystems-textsecure-attachments.s3.amazonaws.com" is not yours, and is not part of your image sending logic?

...slightly worried now!

**Comment by Grunthos** [comment]
I notice it is used here, FWIW:

https://github.com/WhisperSystems/TextSecure-Browser/issues/73

**Comment by Grunthos** [comment]
Hmm...when using WiFi behind a NAT server, it seems to happen. AFAICT, there is nothing very special about the NAT server.

**Comment by moxie0** [comment]
That's the S3 bucket attachments are put in.  Looks like either your device or your network is blocking access.

**Comment by Grunthos** [comment]
Any clues on how to diagnose this? Just going to:

https://whispersystems-textsecure-attachments.s3.amazonaws.com

from my device "succeeds" with XML reporting "access denied", which suggeatscit is getting through to aws.
