### ISSUE TITLE
Notify if incoming message could not be processed 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3468]
Noticed, with a poorly merged HEAD :flushed: 
In fact I skipped the DB migration for the content field for the push table.

All worked fine without crashing, but I didn't get messages, cause of the following Exception.
Sender received delivery receipt. (which is fine https://github.com/WhisperSystems/TextSecure/issues/2027#issuecomment-60410971). 
But here we have the chance to notify the receiving side, that a message from *source* could not be processed.

Case too edgy? Might help with some of the "missing message" issues. Bad installation can happen... 

```
E/SQLiteLog(31362): (1) no such column: content
W/MessageRetrievalService(31362): android.database.sqlite.SQLiteException: no such column: content (code 1): , while compiling: SELECT * FROM push WHERE type = ? AND source = ? AND device_id = ? AND body = ? AND content = ? AND timestamp = ?
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
W/MessageRetrievalService(31362): 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
W/MessageRetrievalService(31362): 	at org.thoughtcrime.securesms.database.PushDatabase.find(PushDatabase.java:104)
W/MessageRetrievalService(31362): 	at org.thoughtcrime.securesms.database.PushDatabase.insert(PushDatabase.java:39)
W/MessageRetrievalService(31362): 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.handleMessage(PushReceivedJob.java:43)
W/MessageRetrievalService(31362): 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.handle(PushReceivedJob.java:35)
W/MessageRetrievalService(31362): 	at org.thoughtcrime.securesms.service.MessageRetrievalService$1.onMessage(MessageRetrievalService.java:89)
W/MessageRetrievalService(31362): 	at org.whispersystems.textsecure.api.TextSecureMessagePipe.read(TextSecureMessagePipe.java:80)
W/MessageRetrievalService(31362): 	at org.thoughtcrime.securesms.service.MessageRetrievalService.run(MessageRetrievalService.java:82)
W/MessageRetrievalService(31362): 	at java.lang.Thread.run(Thread.java:818)

```

**Comment by moxie0** [comment]
Yeah if you alter the source to break the db, shit isn't going to work.
