### ISSUE TITLE
Crash when changing recipient color

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#3508]
TS 2.21.0
Android 4.2.2

When I open a conversation, tap the user and change the color for the contact, TS crashes as soon as I select a color.

I think this is the relevant part of the logfile. No such column: should the database structure be upgraded?

```
07-01 14:30:38.174 E/AndroidRuntime(9661): FATAL EXCEPTION: AsyncTask #4
07-01 14:30:38.174 E/AndroidRuntime(9661): java.lang.RuntimeException: An error occured while executing doInBackground()
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at java.lang.Thread.run(Thread.java:838)
07-01 14:30:38.174 E/AndroidRuntime(9661): Caused by: android.database.sqlite.SQLiteException: no such column: color (code 1): , while compiling: UPDATE recipient_preferences SET color=? WHERE recipient_ids = ?
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:886)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:497)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1563)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1514)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at org.thoughtcrime.securesms.database.RecipientPreferenceDatabase.updateOrInsert(RecipientPreferenceDatabase.java:146)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at org.thoughtcrime.securesms.database.RecipientPreferenceDatabase.setColor(RecipientPreferenceDatabase.java:113)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$ColorChangeListener$1.doInBackground(RecipientPreferenceActivity.java:309)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$ColorChangeListener$1.doInBackground(RecipientPreferenceActivity.java:306)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
07-01 14:30:38.174 E/AndroidRuntime(9661): 	... 4 more
```

**Comment by moxie0** [comment]
You haven't done the DB migration.

**Comment by johanw666** [comment]
Isn't that migration supposed to happen automatically? How do I manually trigger it?

**Comment by moxie0** [comment]
when we cut a release, yes, there will be an automatic migration. this is a branch not even in master. we don't support it.

**Comment by johanw666** [comment]
There are more releases not in master (2.14.5 for example, and 2.20.0 does not have an real release in master) so don't be surprised that people try it. I was able to solve this by addding the field to RecipientPreferenceDatabase.java and increasing the database version but at second thought I will not use it because it will give problems when there are more changes in the database.

Nice addition with those colors for recipients. I've never seen that in another messenger.
