### ISSUE TITLE
KeybardAwareLinearLayout ConcurrentModificationException

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#3559]
On master as of 13eed3baa72ed601edf60b276c376051c3193456

`````
E/AndroidRuntime( 9633): java.util.ConcurrentModificationException
E/AndroidRuntime( 9633): 	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
E/AndroidRuntime( 9633): 	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
E/AndroidRuntime( 9633): 	at org.thoughtcrime.securesms.components.KeyboardAwareLinearLayout.notifyHiddenListeners(KeyboardAwareLinearLayout.java:223)
E/AndroidRuntime( 9633): 	at org.thoughtcrime.securesms.components.KeyboardAwareLinearLayout.onKeyboardClose(KeyboardAwareLinearLayout.java:145)
E/AndroidRuntime( 9633): 	at org.thoughtcrime.securesms.components.KeyboardAwareLinearLayout.onMeasure(KeyboardAwareLinearLayout.java:82)
E/AndroidRuntime( 9633): 	at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 9633): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 9633): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime( 9633): 	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
E/AndroidRuntime( 9633): 	at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 9633): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 9633): 	at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
E/AndroidRuntime( 9633): 	at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 9633): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 9633): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime( 9633): 	at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 9633): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 9633): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime( 9633): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime( 9633): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime( 9633): 	at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 9633): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 9633): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime( 9633): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
E/AndroidRuntime( 9633): 	at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 9633): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
E/AndroidRuntime( 9633): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
E/AndroidRuntime( 9633): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
E/AndroidRuntime( 9633): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime( 9633): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime( 9633): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime( 9633): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime( 9633): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime( 9633): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime( 9633): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 9633): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 9633): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 9633): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 9633): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9633): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9633): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 9633): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`````

**Comment by mcginty** [comment]
should be fixed with the layout fixes PR, was able to reproduce while making that and can't any more
