### ISSUE TITLE
crash: rotate direct capture **a lot** then tap take photo

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3567]
built from 98b99ef5b1b76797e6193bf0ca85fe9430c51637 tested on my GB device. debug log: https://gist.github.com/rhodey/1ec213242a0e172642b3

relevant section seems to be:
```
E/AndroidRuntime( 1193): FATAL EXCEPTION: main
E/AndroidRuntime( 1193): java.lang.NullPointerException
E/AndroidRuntime( 1193): 	at org.thoughtcrime.securesms.components.camera.CameraView.getCameraParameters(CameraView.java:244)
E/AndroidRuntime( 1193): 	at org.thoughtcrime.securesms.components.camera.QuickCamera.takePicture(QuickCamera.java:72)
E/AndroidRuntime( 1193): 	at org.thoughtcrime.securesms.components.camera.QuickAttachmentDrawer$ShutterClickListener.onClick(QuickAttachmentDrawer.java:515)
E/AndroidRuntime( 1193): 	at android.view.View.performClick(View.java:2494)
E/AndroidRuntime( 1193): 	at android.view.View$PerformClick.run(View.java:9105)
E/AndroidRuntime( 1193): 	at android.os.Handler.handleCallback(Handler.java:587)
E/AndroidRuntime( 1193): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1193): 	at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 1193): 	at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime( 1193): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1193): 	at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 1193): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
E/AndroidRuntime( 1193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
E/AndroidRuntime( 1193): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  173):   Force finishing activity org.thoughtcrime.securesms/.ConversationActivity
E/ActivityManager(  173): exception bw.write()java.io.IOException: Transport endpoint is not connected
```

**Comment by rhodey** [comment]
I was also able to reproduce this on kitkat by rapidly opening the camera and immediately tapping the capture picture button.
