### ISSUE TITLE
NPE: switching to SMS when message length is >144 (i.e. SMS message counter toggled)

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3600]
A crash mentioned by @merkste in #3571 

1) Type a string that has at least 145 characters¹ on the compose field
An example string (158 chars):
```
"Bless the Maker and His water," Kynes murmured. "Bless the coming and going of Him. May His passage cleanse the world. May He keep the world for His people."
```

2) Long-press the send arrow and change to SMS mode

3) TS crashes
https://gist.github.com/anonymous/0ee1496d68fdd4fc58ff
```
E/AndroidRuntime( 5058): FATAL EXCEPTION: main
E/AndroidRuntime( 5058): Process: org.thoughtcrime.securesms, PID: 5058
E/AndroidRuntime( 5058): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.view.View.getViewTreeObserver()' on a null object reference
E/AndroidRuntime( 5058): 	at org.thoughtcrime.securesms.TransportOptionsPopup$2.onGlobalLayout(TransportOptionsPopup.java:89)
E/AndroidRuntime( 5058): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
E/AndroidRuntime( 5058): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1881)
E/AndroidRuntime( 5058): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime( 5058): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime( 5058): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime( 5058): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime( 5058): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime( 5058): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime( 5058): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 5058): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5058): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5058): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 5058): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5058): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5058): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5058): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process ( 5058): Sending signal. PID: 5058 SIG: 9
```

TS 2.21.0, Nexus 4, stock 5.1.1

_¹)  >144 characters will show the message length counter in SMS mode_

**Comment by claenn** [comment]
Can't confirm.

Device  : LGE Nexus 5 (hammerhead)
Android : 4.4.4 (8166, slim_hammerhead-userdebug 4.4.4 KTU84Q 8166 test-keys)
Memory  : 58M (0.06% used, 192M max)
Memclass: 192
OS Host : slimgerrit
App     : TextSecure 2.21.0

**Comment by 2-4601** [comment]
I **cannot** reproduce this on my Huawei U8800 device with Android 4.0.4.

@merkste was running:
```
Device  : motorola XT1032 (falcon_retde)
Android : 5.0.2 (1, LXB22.46-28.1)
Memory  : 11M (0.09% used, 96M max)
Memclass: 96
OS Host : ilclbld72
App     : TextSecure 2.21.0
```
Maybe this is a Lollipop issue?

**Comment by McLoo** [comment]
5.0.2 confirmed

**Comment by 5boro** [comment]
Cannot reproduce on 5.1
