### ISSUE TITLE
TS crashes while updating database after upgrade to 2.23

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/TextSecure#3696]
See log: https://gist.github.com/1baa4ebc4f865ef3f3a1

**Comment by agrajaghh** [comment]
```
E/AndroidRuntime(14840): Caused by: java.lang.AssertionError: java.io.FileNotFoundException: /data/data/org.thoughtcrime.securesms/files/prekeys/7823947: open failed: EMFILE (Too many open files)
E/AndroidRuntime(14840): 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.storePreKey(TextSecurePreKeyStore.java:98)
E/AndroidRuntime(14840): 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.migrateRecords(TextSecurePreKeyStore.java:148)
E/AndroidRuntime(14840): 	at org.thoughtcrime.securesms.DatabaseUpgradeActivity$DatabaseUpgradeTask.doInBackground(DatabaseUpgradeActivity.java:186)
E/AndroidRuntime(14840): 	at org.thoughtcrime.securesms.DatabaseUpgradeActivity$DatabaseUpgradeTask.doInBackground(DatabaseUpgradeActivity.java:130)
E/AndroidRuntime(14840): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(14840): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(14840): 	... 4 more

```

**Comment by piratenpanda** [comment]
This happens all the time, can't start textsecure any more.

**Comment by agrajaghh** [comment]
@moxie0 looks like `recordFile.close()` isn't reached when the `IOException` is thrown at https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/crypto/storage/TextSecurePreKeyStore.java#L199

**Comment by piratenpanda** [comment]
There's probably no way to downgrade without losing data, right?

**Comment by piratenpanda** [comment]
Updating my rom and trying again lead to several crashes but in the end TS is now running again. Strange
