### ISSUE TITLE
Crash on start due to old session files

### ISSUE THREAD

**Issue by DorianScholz** [WhisperSystems/TextSecure#3811]
Since the recent update to 2.23.3 TextSecure crashed for me directly on the start of the app before even showing the main screen.
LogCat pointed to https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/crypto/storage/TextSecureSessionStore.java#L71:

    07-27 14:07:19.422 E/AndroidRuntime(16231): Process: org.thoughtcrime.securesms, PID: 16231
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.loadSession(TextSecureSessionStore.java:71)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.containsSession(TextSecureSessionStore.java:112)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.thoughtcrime.securesms.crypto.storage.TextSecureAxolotlStore.containsSession(TextSecureAxolotlStore.java:91)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessage(TextSecureMessageSender.java:377)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessages(TextSecureMessageSender.java:361)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:299)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:123)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:115)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:62)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
    07-27 14:07:19.422 E/AndroidRuntime(16231): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
    07-27 14:07:19.432 E/ActivityManager(968): App crashed! Process: org.thoughtcrime.securesms

From the code there it seems the session files in the /data/data/org.thoughtcrime.securesms/files/sessions-v2 dir should have already been migrated to version 3, which was not the case for me.
The files in this location were mostly version 2 and even some version 1 on my phone...
After I deleted these session files I was able to start the app again.

But sending a secure message afterward resulted in it directly crashing again.
And now again, it crashes on start, when trying to resend the pending message.
Error log:

    07-27 15:16:05.635 E/ActivityManager(968): App crashed! Process: org.thoughtcrime.securesms
    07-27 15:16:05.635 E/AndroidRuntime(29474): Process: org.thoughtcrime.securesms, PID: 29474
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.thoughtcrime.securesms.crypto.IdentityKeyUtil.getIdentityKeyPair(IdentityKeyUtil.java:71)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.thoughtcrime.securesms.crypto.storage.TextSecureIdentityKeyStore.getIdentityKeyPair(TextSecureIdentityKeyStore.java:23)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.thoughtcrime.securesms.crypto.storage.TextSecureAxolotlStore.getIdentityKeyPair(TextSecureAxolotlStore.java:36)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessage(TextSecureMessageSender.java:385)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessages(TextSecureMessageSender.java:361)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:299)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:123)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:115)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:62)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
    07-27 15:16:05.635 E/AndroidRuntime(29474): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
    07-27 15:16:05.635 W/ActivityManager(968):   Force finishing activity org.thoughtcrime.securesms/.ConversationListActivity

Both crashes seem to point to this commit:
https://github.com/WhisperSystems/TextSecure/commit/8d9ae731ef4124dbb3900e0b62cc98199b64c783

Any help on getting TextSecure working again are appreciated.
I can provide more logs, and also backups of the deleted session files, if that helps.

**Comment by DorianScholz** [comment]
Found the problem.
I had a bad setting of 999 in the org.thoughtcrime.securesms_preferences.xml file for last_version_code, probably due to some self compiled version I used about 2 years ago...
Setting it back to 45 and restarting the app started a database upgrade, which seems to have solved this problem.
Funny though, that I did not have any other problems in the last two year, skipping all the database upgrades ;-)
Sorry for the noise though!
