### ISSUE TITLE
twitched direct capture to crash

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3895]
As usual I had nothing better to do than testing how robust my display glass is right at the emoji and direct capture button, with rappppid tapping

Just did fast changes between camera and emoji and sometimes keyboard, as you can get from to log.

HTC One S on CM 12.1
2.25.0 branch at https://github.com/WhisperSystems/TextSecure/commit/a820500ae010a5b77e6c456640961925d14a7c39

relevant log part:

```
08-05 23:55:20.455  10855-10855/org.thoughtcrime.securesms D/AndroidRuntime? Shutting down VM
08-05 23:55:20.479  10855-10855/org.thoughtcrime.securesms E/AndroidRuntime? FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms, PID: 10855
    java.lang.RuntimeException: startPreview failed
            at android.hardware.Camera.startPreview(Native Method)
            at org.thoughtcrime.securesms.components.camera.CameraView.startPreview(CameraView.java:313)
            at org.thoughtcrime.securesms.components.camera.CameraView.access$1200(CameraView.java:47)
            at org.thoughtcrime.securesms.components.camera.CameraView$4.onPostMain(CameraView.java:303)
            at org.thoughtcrime.securesms.components.camera.CameraView$4.onPostMain(CameraView.java:291)
            at org.thoughtcrime.securesms.components.camera.CameraView$SerializedAsyncTask$2.run(CameraView.java:465)
            at org.thoughtcrime.securesms.components.camera.CameraView$SerializedAsyncTask$3.run(CameraView.java:484)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
08-05 23:55:35.359  10855-12039/org.thoughtcrime.securesms W/WebSocketConnection? Sending keep alive...
``` 

some more context:
```
08-05 23:54:47.562  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:47.562  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:47.563  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:47.563  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:47.564  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:47.564  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:47.726  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardOpen(324)
08-05 23:54:47.727  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:48.163  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:54:48.165  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:48.165  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:48.166  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:48.166  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:48.219  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() queued
08-05 23:54:48.284  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:48.408  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() queued
08-05 23:54:48.587  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:48.587  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:48.592  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:48.592  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:48.619  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:48.620  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:54:48.631  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:54:48.631  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:54:48.631  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:54:48.794  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:48.803  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardOpen(388)
08-05 23:54:48.926  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:54:49.201  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:54:49.210  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:49.210  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:49.214  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:49.303  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:49.414  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() queued
08-05 23:54:49.440  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:49.468  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() queued
08-05 23:54:49.764  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:54:49.765  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:54:49.765  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:54:49.765  10855-10976/org.thoughtcrime.securesms W/CameraView﹕ waiting. camera? true previewSize? false prevewStrategy? true
08-05 23:54:49.770  10855-11373/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Application level read timeout...
08-05 23:54:49.771  10855-11373/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Network requirement: true, active activities: 1, push pending: 0
08-05 23:54:49.771  10855-11373/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Reading message...
08-05 23:54:50.059  10855-10855/org.thoughtcrime.securesms W/ConversationActivity﹕ onConfigurationChanged(2)
08-05 23:54:50.086  10855-10855/org.thoughtcrime.securesms W/QuickAttachmentDrawer﹕ updateControlsView()
08-05 23:54:50.099  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:50.105  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ rotation changed
08-05 23:54:50.105  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:54:51.129  10855-10855/org.thoughtcrime.securesms W/ConversationActivity﹕ onConfigurationChanged(1)
08-05 23:54:51.134  10855-10855/org.thoughtcrime.securesms W/QuickAttachmentDrawer﹕ updateControlsView()
08-05 23:54:51.140  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ rotation changed
08-05 23:54:51.140  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:54:53.528  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:54.839  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:54.901  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() queued
08-05 23:54:54.942  10855-10855/org.thoughtcrime.securesms W/SurfacePreviewStrategy﹕ surfaceChanged()
08-05 23:54:54.947  10855-10855/org.thoughtcrime.securesms W/SurfacePreviewStrategy﹕ attach(Camera)
08-05 23:54:54.949  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() completed
08-05 23:54:55.373  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() completed
08-05 23:54:55.660  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:54:55.730  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:55.762  10855-10855/org.thoughtcrime.securesms W/SurfacePreviewStrategy﹕ surfaceChanged()
08-05 23:54:55.792  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() queued
08-05 23:54:56.350  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:54:56.351  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:54:56.351  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:54:56.548  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:54:57.074  10855-10855/org.thoughtcrime.securesms W/ConversationActivity﹕ onConfigurationChanged(2)
08-05 23:54:57.082  10855-10855/org.thoughtcrime.securesms W/QuickAttachmentDrawer﹕ updateControlsView()
08-05 23:54:57.086  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:54:57.087  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ rotation changed
08-05 23:54:57.088  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:54:57.242  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:54:57.246  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:54:57.248  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:54:57.453  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:54:58.124  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:54:58.124  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:54:58.124  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:54:58.257  10855-10855/org.thoughtcrime.securesms W/ConversationActivity﹕ onConfigurationChanged(1)
08-05 23:54:58.260  10855-10855/org.thoughtcrime.securesms W/QuickAttachmentDrawer﹕ updateControlsView()
08-05 23:54:58.271  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ rotation changed
08-05 23:54:58.271  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:54:58.330  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:54:58.330  10855-10974/org.thoughtcrime.securesms W/CameraView﹕ skipping task, preconditions not met in onWait()
08-05 23:54:58.331  10855-10974/org.thoughtcrime.securesms W/CameraView﹕ skipping task, preconditions not met in onWait()
08-05 23:54:59.139  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:54:59.140  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:54:59.140  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:54:59.298  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:54:59.367  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:54:59.986  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:54:59.987  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:54:59.987  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:55:00.194  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:55:00.827  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:55:00.827  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:55:00.827  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:55:00.898  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:00.898  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:00.900  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:00.900  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:00.954  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:00.954  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:01.059  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:55:01.158  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardOpen(922)
08-05 23:55:01.158  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:55:01.800  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:55:01.800  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:55:01.800  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:55:01.995  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() completed
08-05 23:55:02.215  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:55:02.216  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:55:02.493  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:02.493  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:02.596  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardOpen(388)
08-05 23:55:02.596  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:55:02.750  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() queued
08-05 23:55:02.750  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ initPreview() queued
08-05 23:55:02.750  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() completed
08-05 23:55:02.753  10855-10977/org.thoughtcrime.securesms W/CameraView﹕ waiting. camera? true previewSize? false prevewStrategy? true
08-05 23:55:02.811  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:55:02.812  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:55:02.978  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:02.978  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:03.095  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardOpen(388)
08-05 23:55:03.095  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:55:03.229  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:55:03.230  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:55:03.369  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:03.369  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:03.468  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardOpen(388)
08-05 23:55:03.468  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:55:03.630  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardClose()
08-05 23:55:03.631  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ showing emoji drawer with height 388
08-05 23:55:03.799  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:03.799  10855-10855/org.thoughtcrime.securesms E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-05 23:55:03.890  10855-10855/org.thoughtcrime.securesms W/EmojiDrawer﹕ hide()
08-05 23:55:03.953  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onResume() queued
08-05 23:55:03.973  10855-10855/org.thoughtcrime.securesms W/KeyboardAwareLinearLayout﹕ onKeyboardOpen(388)
08-05 23:55:04.016  10855-10855/org.thoughtcrime.securesms W/SurfacePreviewStrategy﹕ surfaceChanged()
08-05 23:55:04.052  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ onPause() queued
08-05 23:55:04.073  10855-10855/org.thoughtcrime.securesms W/SurfacePreviewStrategy﹕ attach(Camera)
08-05 23:55:04.075  10855-10855/org.thoughtcrime.securesms W/CameraView﹕ previewCreated() completed
08-05 23:55:20.455  10855-10855/org.thoughtcrime.securesms D/AndroidRuntime﹕ Shutting down VM
08-05 23:55:20.479  10855-10855/org.thoughtcrime.securesms E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms, PID: 10855
    java.lang.RuntimeException: startPreview failed
            at android.hardware.Camera.startPreview(Native Method)
            at org.thoughtcrime.securesms.components.camera.CameraView.startPreview(CameraView.java:313)
            at org.thoughtcrime.securesms.components.camera.CameraView.access$1200(CameraView.java:47)
            at org.thoughtcrime.securesms.components.camera.CameraView$4.onPostMain(CameraView.java:303)
            at org.thoughtcrime.securesms.components.camera.CameraView$4.onPostMain(CameraView.java:291)
            at org.thoughtcrime.securesms.components.camera.CameraView$SerializedAsyncTask$2.run(CameraView.java:465)
            at org.thoughtcrime.securesms.components.camera.CameraView$SerializedAsyncTask$3.run(CameraView.java:484)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
08-05 23:55:35.359  10855-12039/org.thoughtcrime.securesms W/WebSocketConnection﹕ Sending keep alive...
08-05 23:55:35.484  10855-12038/org.thoughtcrime.securesms W/OkHttpClientWrapper﹕ onMessage: BINARY
08-05 23:55:35.484  10855-12038/org.thoughtcrime.securesms W/WebSocketConnection﹕ WSC onMessage()
08-05 23:55:35.484  10855-12038/org.thoughtcrime.securesms W/WebSocketConnection﹕ Message Type: 2
08-05 23:55:49.772  10855-11373/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Application level read timeout...
08-05 23:55:49.777  10855-11373/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Network requirement: true, active activities: 1, push pending: 0
08-05 23:55:49.783  10855-11373/org.thoughtcrime.securesms W/MessageRetrievalService﹕ Reading message...
08-05 23:56:30.359  10855-12039/org.thoughtcrime.securesms W/WebSocketConnection﹕ Sending keep alive...
08-05 23:56:30.483  10855-12038/org.thoughtcrime.securesms W/OkHttpClientWrapper﹕ onMessage: BINARY
08-05 23:56:30.483  10855-12038/org.thoughtcrime.securesms W/WebSocketConnection﹕ WSC onMessage()
08-05 23:56:30.483  10855-12038/org.thoughtcrime.securesms W/WebSocketConnection﹕ Message Type: 2

```

**Comment by McLoo** [comment]
Trying to repro I somehow killed the camera. 
Reported already about killied camera in #3694, maybe this log now helps
https://gist.github.com/db3838c837364baa60cd

**Comment by mcginty** [comment]
huh, I actually can't get this one to reproduce but will give a shot at it given the debug log. I don't think this is a 2.25.0 critical bug, so I'll get a PR out and @McLoo if you want to test that once it's out I'd greatly appreciate your ninja tap skills

**Comment by McLoo** [comment]
@mcginty sure thing 🙏
Just need to find the way to reproduce

**Comment by McLoo** [comment]
Ah!  reproduced. 
https://gist.github.com/53db179bc3a2b7454c09

**Comment by McLoo** [comment]
wasn't able to reproduce in my Z1 compact
Could be a CM 12.1 or a hardware issue of the HTC One S?!

**Comment by mcginty** [comment]
YAY! ok cool. I still can't reproduce but trust you to :P. Will get a PR out shortlyyyyyyy
