### ISSUE TITLE
crash on receive of textsecure group message

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#4032]
received a textsecure group message while outside the app, the notification showed in the drawer for a second, then TS crashed. stock ROM

https://gist.github.com/anonymous/a8f29d89f1694d9a06af

```
--------- beginning of crash
E/AndroidRuntime( 5677): FATAL EXCEPTION: main
E/AndroidRuntime( 5677): Process: org.thoughtcrime.securesms, PID: 5677
E/AndroidRuntime( 5677): java.lang.RuntimeException: Error receiving broadcast Intent { act=org.thoughtcrime.securesms.database.GroupDatabase.UPDATE flg=0x10 } in org.thoughtcrime.securesms.ConversationActivity$17@38c85fd5
E/AndroidRuntime( 5677): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
E/AndroidRuntime( 5677): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 5677): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5677): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5677): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 5677): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5677): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5677): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5677): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 5677): Caused by: java.lang.IllegalArgumentException: YOu must call this method on a background thread
E/AndroidRuntime( 5677): 	at com.bumptech.glide.util.Util.assertBackgroundThread(Util.java:144)
E/AndroidRuntime( 5677): 	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:169)
E/AndroidRuntime( 5677): 	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
E/AndroidRuntime( 5677): 	at org.thoughtcrime.securesms.contacts.avatars.ContactPhotoFactory.getContactPhoto(ContactPhotoFactory.java:44)
E/AndroidRuntime( 5677): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getIndividualRecipientDetails(RecipientProvider.java:143)
E/AndroidRuntime( 5677): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipientDetailsSync(RecipientProvider.java:129)
E/AndroidRuntime( 5677): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipient(RecipientProvider.java:82)
E/AndroidRuntime( 5677): 	at org.thoughtcrime.securesms.recipients.RecipientProvider.getRecipients(RecipientProvider.java:96)
E/AndroidRuntime( 5677): 	at org.thoughtcrime.securesms.recipients.RecipientFactory.getRecipientsForIds(RecipientFactory.java:66)
E/AndroidRuntime( 5677): 	at org.thoughtcrime.securesms.ConversationActivity$17.onReceive(ConversationActivity.java:886)
E/AndroidRuntime( 5677): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
E/AndroidRuntime( 5677): 	... 8 more
```

**Comment by mcginty** [comment]
@moxie0 it looks like in ConversationActivity.java the groupUpdateReceiver does a synchronous recipient resolution when it receives a group context update. Any reason that can't be async?
