### ISSUE TITLE
thumbnailview crash

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#4119]
`````
E/AndroidRuntime(20275): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}: android.view.InflateException: Binary XML file line #35: Error inflating class org.thoughtcrime.securesms.components.ThumbnailView
E/AndroidRuntime(20275): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime(20275): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime(20275): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(20275): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime(20275): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(20275): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(20275): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(20275): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20275): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(20275): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(20275): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(20275): Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class org.thoughtcrime.securesms.components.ThumbnailView
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime(20275): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
E/AndroidRuntime(20275): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
E/AndroidRuntime(20275): 	at org.thoughtcrime.securesms.ConversationActivity.onCreate(ConversationActivity.java:208)
E/AndroidRuntime(20275): 	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:46)
E/AndroidRuntime(20275): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(20275): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(20275): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime(20275): 	... 10 more
E/AndroidRuntime(20275): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(20275): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime(20275): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime(20275): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime(20275): 	... 25 more
E/AndroidRuntime(20275): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.thoughtcrime.securesms.components.TransferControlView.setClickable(boolean)' on a null object reference
E/AndroidRuntime(20275): 	at org.thoughtcrime.securesms.components.ThumbnailView.setClickable(ThumbnailView.java:82)
E/AndroidRuntime(20275): 	at android.view.View.setOnClickListener(View.java:4724)
E/AndroidRuntime(20275): 	at org.thoughtcrime.securesms.components.ThumbnailView.<init>(ThumbnailView.java:70)
E/AndroidRuntime(20275): 	at org.thoughtcrime.securesms.components.ThumbnailView.<init>(ThumbnailView.java:62)
E/AndroidRuntime(20275): 	... 28 more
W/ActivityManager(  749):   Force finishing activity 1 org.thoughtcrime.securesms/.ConversationActivity
`````

**Comment by jeremymasters** [comment]
Is this what's causing me to only see the icon for a video instead of a thumbnail of the video in a message with attached video?  Wanted to check before I wrote something up.

**Comment by 2-4601** [comment]
@jeremymasters No.
This bug is not even in 2.27.2 (yet) and there's already a PR to fix this so this will probably never appear in a release version.
