### ISSUE TITLE
signal branch bluetooth NPE

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/TextSecure#4141]
```
                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.bluetooth.BluetoothDevice.getAddress()' on a
                             null object reference
                         E      at android.os.Parcel.readException(Parcel.java:1556)
                         E      at android.os.Parcel.readException(Parcel.java:1499)
                         E      at android.media.IAudioService$Stub$Proxy.startBluetoothSco(IAudioService.java:1698)
                         E      at android.media.AudioManager.startBluetoothSco(AudioManager.java:1511)
                         E      at org.thoughtcrime.redphone.audio.OutgoingRinger.onPrepared(OutgoingRinger.java:138)
                         E      at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2573)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:211)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5321)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by moxie0** [comment]
fixed in 3.0.0
