### ISSUE TITLE
signal call: login failed error

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/TextSecure#4183]
Signal 3.0.0. Android 4.4.4. 

Was trying to call  a contact on iOS Signal. Texting with this contact works fine.

https://gist.github.com/8b072e3c8becbc30ee5c

**Comment by dcherian** [comment]
````
W/RedPhone(25012): Binding to RedPhoneService...
E/MediaPlayer(25012): Should have subtitle controller already set
W/MmsSmsDatabase(25012): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC)
W/SignalingSocket(25012): Connected to: 66.175.212.82
D/SignalingSocket(25012): Sending signal...
W/LineReader(25012): Chomped line: 48 54 54 50 2f 31 2e 30 20 34 30 31 20 55 6e 61 75 74 68 6f 72 69 7a 65 64 
W/LineReader(25012): Buffer length: 48
W/LineReader(25012): Writing remaining to buffer, offset: 27 Length: 21
W/LineReader(25012): Chomped line: 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 30 
W/LineReader(25012): Buffer length: 21
W/LineReader(25012): Writing remaining to buffer, offset: 19 Length: 2
W/LineReader(25012): Chomped line: 
W/LineReader(25012): Buffer length: 2
W/InitiatingCallManager(25012): org.thoughtcrime.redphone.signaling.LoginFailedException: Initiate threw 401
W/InitiatingCallManager(25012): 	at org.thoughtcrime.redphone.signaling.SignalingSocket.initiateConnection(SignalingSocket.java:184)
W/InitiatingCallManager(25012): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:77)
W/RedPhone(25012): Got message from service: 14
W/RedPhoneService(25012): termination stack
W/RedPhoneService(25012): java.lang.Exception
W/RedPhoneService(25012): 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:340)
W/RedPhoneService(25012): 	at org.thoughtcrime.redphone.RedPhoneService.notifyLoginFailed(RedPhoneService.java:487)
W/RedPhoneService(25012): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:103)
D/LockManager(25012): Entered Lock State: PARTIAL
D/AccelerometerListener(25012): enable(false)
D/org.thoughtcrime.redphone.audio.IncomingRinger(25012): Cancelling vibrator
````

**Comment by dcherian** [comment]
Redphone gives me the same error.

**Comment by moxie0** [comment]
did you re-install/re-register with redphone after the signal upgrade?

**Comment by dcherian** [comment]
No I didn't do anything. Just updated to Signal.

**Comment by moxie0** [comment]
Weird.  Unregistering and reregistering should fix it (Advanced -> Signal), but I'm not sure how you got into that state. Anything else weird about the upgrade process or your install?

**Comment by dcherian** [comment]
Nothing weird happened during the upgrade. I did make a test call and hung up before anything happened. Could that have done something?

my phone is rooted and I have xposed.

**Comment by moxie0** [comment]
where are you geographically located? (you can also email me at moxie.github@moxie.org if you don't want to post that info here for any reason).

**Comment by dcherian** [comment]
Cambridge, MA

**Comment by dcherian** [comment]
OK. Just got incoming call from iOS signal and it worked well. Now when I try to call out, it gives me "Server Failed" which I assume has already been fixed.

**Comment by moxie0** [comment]
@dcherian For clarity, did you uninstall and reinstall, or did it just start working?

**Comment by dcherian** [comment]
I did nothing. Just picked up the incoming call.

**Comment by moxie0** [comment]
Cool, and would you mind trying to initiate a call again to see if they work now?

**Comment by dcherian** [comment]
Still server failed. Happens really quickly.

https://gist.github.com/anonymous/53c8decd367e32c1766f 

My log is really polluted btw

**Comment by moxie0** [comment]
hmm looks like the top of the log (where the action is) got cut off

**Comment by dcherian** [comment]
Ugh. OK. That contact has gone to sleep and I dont know anyone else with Signal. So I'll try tomorrow and update this thread if it doesn't work.

**Comment by dcherian** [comment]
Everything works OK now. So closing.

**Comment by mderazon** [comment]
Can you share how you sorted it out eventually ? (Login failed)

**Comment by dcherian** [comment]
I think it was d some server problem that was fixed.I didn't do anything

**Comment by mderazon** [comment]
Uninstalled and installed again and then problem solved
