### ISSUE TITLE
NPE when touching the swipe to answer/reject area in an incoming call

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#4203]
When I get an incoming call and I try to answer, Signal crashes every time on my ICS device.
It crashes immediately after I lay my finger on the swipe-to-answer area of the screen.
![npe potato](https://cloud.githubusercontent.com/assets/174176/10268668/66b7504a-6ac8-11e5-9799-e8de90229cde.png)

logcat (not filtered):
https://gist.github.com/anonymous/7f0329505ee8efc6f474
```
10-04 18:26:36.440 E/AndroidRuntime( 5183): FATAL EXCEPTION: main
10-04 18:26:36.440 E/AndroidRuntime( 5183): java.lang.NullPointerException
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:513)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:392)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:544)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.animation.ValueAnimator.start(ValueAnimator.java:934)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.animation.ValueAnimator.start(ValueAnimator.java:957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.animation.ObjectAnimator.start(ObjectAnimator.java:370)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at org.thoughtcrime.redphone.util.multiwaveview.Tweener.to(Tweener.java:127)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at org.thoughtcrime.redphone.util.multiwaveview.MultiWaveView.showTargets(MultiWaveView.java:507)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at org.thoughtcrime.redphone.util.multiwaveview.MultiWaveView.switchToState(MultiWaveView.java:288)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at org.thoughtcrime.redphone.util.multiwaveview.MultiWaveView.trySwitchToFirstTouchState(MultiWaveView.java:830)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at org.thoughtcrime.redphone.util.multiwaveview.MultiWaveView.handleDown(MultiWaveView.java:699)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at org.thoughtcrime.redphone.util.multiwaveview.MultiWaveView.onTouchEvent(MultiWaveView.java:668)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.View.dispatchTouchEvent(View.java:5541)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1912)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1371)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2364)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1860)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.View.dispatchPointerEvent(View.java:5721)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2890)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2466)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:845)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2475)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.os.Looper.loop(Looper.java:137)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at android.app.ActivityThread.main(ActivityThread.java:4424)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
10-04 18:26:36.440 E/AndroidRuntime( 5183): 	at dalvik.system.NativeStart.main(Native Method)
```

Signal 3.0.1
Huawei U8800, 4.0.4

**Comment by moxie0** [comment]
@2-4601 Thanks! Any chance you could retest with this commit on your ICS device?

**Comment by 2-4601** [comment]
Just tested and it fixes the crash, thanks :+1:

**Comment by jiangyanlily** [comment]
@moxie0 any good way to support animation on Android 4.0.x instead of not using animation?
